msgid ""
msgstr ""
"Project-Id-Version: ubuntu-translations\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2019-04-11 20:13+0000\n"
"PO-Revision-Date: 2019-08-27 10:47\n"
"Last-Translator: Andriy Poznakhovskyy (Andriy_Crowdin)\n"
"Language-Team: Russian\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Launchpad-Export-Date: 2019-05-11 12:08+0000\n"
"X-Generator: crowdin.com\n"
"Language: ru_RU\n"
"Plural-Forms: nplurals=4; plural=((n%10==1 && n%100!=11) ? 0 : ((n%10 >= 2 && n%10 <=4 && (n%100 < 12 || n%100 > 14)) ? 1 : ((n%10 == 0 || (n%10 >= 5 && n%10 <=9)) || (n%100 >= 11 && n%100 <= 14)) ? 2 : 3));\n"
"X-Crowdin-Project: ubuntu-translations\n"
"X-Crowdin-Language: ru\n"
"X-Crowdin-File: /master/rosetta-eoan/en_GB/LC_MESSAGES/apport.po\n"

#: ../debian/tmp/usr/share/apport/apport-kde.py:186
#: ../debian/tmp/usr/share/apport/apport-gtk.py:181
#: ../debian/tmp/usr/bin/apport-cli.py:194 ../kde/apport-kde.py:186
#: ../bin/apport-cli.py:194 ../gtk/apport-gtk.py:181 ../gtk/apport-gtk.ui.h:6
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:6
msgid "Send problem report to the developers?"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:194
#: ../debian/tmp/usr/share/apport/apport-gtk.py:188 ../kde/apport-kde.py:194
#: ../gtk/apport-gtk.py:188 ../gtk/apport-gtk.ui.h:14
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:14
msgid "Send"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:200
#: ../debian/tmp/usr/share/apport/apport-kde.py:238
#: ../debian/tmp/usr/share/apport/apport-gtk.py:169 ../kde/apport-kde.py:200
#: ../kde/apport-kde.py:238 ../gtk/apport-gtk.py:169
#, python-format
msgid "Sorry, %s has experienced an internal error."
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:208
#: ../debian/tmp/usr/share/apport/apport-gtk.py:259 ../kde/apport-kde.py:208
#: ../gtk/apport-gtk.py:259
#, python-format
msgid "Package: %s"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:214
#: ../debian/tmp/usr/share/apport/apport-gtk.py:265 ../kde/apport-kde.py:214
#: ../gtk/apport-gtk.py:265
msgid "Sorry, a problem occurred while installing software."
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:220
#: ../debian/tmp/usr/share/apport/apport-gtk.py:274
#: ../debian/tmp/usr/share/apport/apport-gtk.py:289 ../kde/apport-kde.py:220
#: ../gtk/apport-gtk.py:274 ../gtk/apport-gtk.py:289
#, python-format
msgid "The application %s has experienced an internal error."
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:223
#: ../debian/tmp/usr/share/apport/apport-gtk.py:277 ../kde/apport-kde.py:223
#: ../gtk/apport-gtk.py:277
#, python-format
msgid "The application %s has closed unexpectedly."
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:231
#: ../debian/tmp/usr/share/apport/apport-kde.py:244
#: ../debian/tmp/usr/share/apport/apport-gtk.py:216 ../kde/apport-kde.py:231
#: ../kde/apport-kde.py:244 ../gtk/apport-gtk.py:216
msgid "Continue"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:234 ../kde/apport-kde.py:234
msgid "Leave Closed"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:235
#: ../debian/tmp/usr/share/apport/apport-kde.py:381 ../kde/apport-kde.py:235
#: ../kde/apport-kde.py:381
msgid "Relaunch"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:241
#: ../debian/tmp/usr/share/apport/apport-gtk.py:297 ../kde/apport-kde.py:241
#: ../gtk/apport-gtk.py:297 ../gtk/apport-gtk.ui.h:7
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:7
msgid "If you notice further problems, try restarting the computer."
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:245
#: ../debian/tmp/usr/share/apport/apport-gtk.py:299 ../kde/apport-kde.py:245
#: ../gtk/apport-gtk.py:299
msgid "Ignore future problems of this type"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:289
#: ../debian/tmp/usr/share/apport/apport-gtk.py:579 ../kde/apport-kde.py:289
#: ../gtk/apport-gtk.py:579
msgid "Hide Details"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:292
#: ../debian/tmp/usr/share/apport/apport-gtk.py:204
#: ../debian/tmp/usr/share/apport/apport-gtk.py:575 ../kde/apport-kde.py:292
#: ../gtk/apport-gtk.py:204 ../gtk/apport-gtk.py:575 ../gtk/apport-gtk.ui.h:11
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:11
msgid "Show Details"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:315 ../kde/apport-kde.py:315
msgid "Username:"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:316 ../kde/apport-kde.py:316
msgid "Password:"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:363
#: ../debian/tmp/usr/share/apport/apport-gtk.py:146
#: ../debian/tmp/usr/bin/apport-cli.py:166 ../kde/apport-kde.py:363
#: ../bin/apport-cli.py:166 ../gtk/apport-gtk.py:146
msgid "(binary data)"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:406 ../kde/apport-kde.py:406
msgid "Collecting Problem Information"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:407
#: ../debian/tmp/usr/bin/apport-cli.py:254 ../kde/apport-kde.py:407
#: ../bin/apport-cli.py:254
msgid "Collecting problem information"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:408 ../kde/apport-kde.py:408
msgid "The collected information can be sent to the developers to improve the application. This might take a few minutes."
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:434 ../kde/apport-kde.py:434
msgid "Uploading Problem Information"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:435
#: ../debian/tmp/usr/bin/apport-cli.py:267 ../kde/apport-kde.py:435
#: ../bin/apport-cli.py:267 ../gtk/apport-gtk.ui.h:17
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:17
msgid "Uploading problem information"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:436 ../kde/apport-kde.py:436
#: ../gtk/apport-gtk.ui.h:19 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:19
msgid "The collected information is being sent to the bug tracking system. This might take a few minutes."
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:469
#: ../debian/tmp/usr/share/apport/apport-kde.py:504
#: ../debian/tmp/usr/share/apport/apport-kde.py:524 ../kde/apport-kde.py:469
#: ../kde/apport-kde.py:504 ../kde/apport-kde.py:524 ../gtk/apport-gtk.ui.h:1
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:1
msgid "Apport"
msgstr ""

#: ../gtk/apport-gtk.desktop.in.h:1 ../kde/apport-kde.desktop.in.h:1
#: ../kde/apport-kde-mime.desktop.in.h:1
msgid "Report a problem..."
msgstr ""

#: ../gtk/apport-gtk.desktop.in.h:2 ../kde/apport-kde.desktop.in.h:2
#: ../kde/apport-kde-mime.desktop.in.h:2
msgid "Report a malfunction to the developers"
msgstr ""

#: ../apport/com.ubuntu.apport.policy.in.h:1
msgid "Collect system information"
msgstr ""

#: ../apport/com.ubuntu.apport.policy.in.h:2
msgid "Authentication is required to collect system information for this problem report"
msgstr ""

#: ../apport/com.ubuntu.apport.policy.in.h:3
msgid "System problem reports"
msgstr ""

#: ../apport/com.ubuntu.apport.policy.in.h:4
msgid "Please enter your password to access problem reports of system programs"
msgstr ""

#: ../data/general-hooks/ubuntu.py:184
#: ../debian/tmp/usr/share/apport/general-hooks/ubuntu.py:184
msgid "An Ubuntu package has a file conflict with a package that is not a genuine Ubuntu package."
msgstr ""

#: ../data/general-hooks/ubuntu.py:192
#: ../debian/tmp/usr/share/apport/general-hooks/ubuntu.py:192
msgid "You have already encountered this package installation failure."
msgstr ""

#: ../data/general-hooks/ubuntu.py:208
#: ../debian/tmp/usr/share/apport/general-hooks/ubuntu.py:208
msgid "Your system was initially configured with grub version 2, but you have removed it from your system in favor of grub 1 without configuring it.  To ensure your bootloader configuration is updated whenever a new kernel is available, open a terminal and run:\n\n"
"      sudo apt-get install grub-pc\n"
msgstr ""

#: ../kde/apport-kde-mimelnk.desktop.in.h:1
msgid "Apport crash file"
msgstr ""

#: ../debian/tmp/usr/share/apport/kernel_oops.py:29 ../data/kernel_oops.py:29
msgid "Your system might become unstable now and might need to be restarted."
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:34 ../bin/apport-retrace.py:34
msgid "Do not put the new traces into the report, but write them to stdout."
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:36 ../bin/apport-retrace.py:36
msgid "Start an interactive gdb session with the report's core dump (-o ignored; does not rewrite report)"
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:38 ../bin/apport-retrace.py:38
msgid "Write modified report to given file instead of changing the original report"
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:41 ../bin/apport-retrace.py:41
msgid "Remove the core dump from the report after stack trace regeneration"
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:43 ../bin/apport-retrace.py:43
msgid "Override report's CoreFile"
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:45 ../bin/apport-retrace.py:45
msgid "Override report's ExecutablePath"
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:47 ../bin/apport-retrace.py:47
msgid "Override report's ProcMaps"
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:49 ../bin/apport-retrace.py:49
msgid "Rebuild report's Package information"
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:51 ../bin/apport-retrace.py:51
msgid "Build a temporary sandbox and download/install the necessary packages and debug symbols in there; without this option it assumes that the necessary packages and debug symbols are already installed in the system. The argument points to the packaging system configuration base directory; if you specify \"system\", it will use the system configuration files, but will then only be able to retrace crashes that happened on the currently running release."
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:53 ../bin/apport-retrace.py:53
msgid "Build another temporary sandbox for installing gdb and its dependencies using the same release as the report rather than whatever version of gdb you have installed."
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:55 ../bin/apport-retrace.py:55
msgid "Report download/install progress when installing packages into sandbox"
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:57 ../bin/apport-retrace.py:57
msgid "Prepend timestamps to log messages, for batch operation"
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:59 ../bin/apport-retrace.py:59
msgid "Create and use third-party repositories from origins specified in reports"
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:61 ../bin/apport-retrace.py:61
msgid "Cache directory for packages downloaded in the sandbox"
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:63 ../bin/apport-retrace.py:63
msgid "Directory for unpacked packages. Future runs will assume that any already downloaded package is also extracted to this sandbox."
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:65 ../bin/apport-valgrind.py:66
#: ../bin/apport-retrace.py:65 ../debian/tmp/usr/bin/apport-valgrind.py:66
msgid "Install an extra package into the sandbox (can be specified multiple times)"
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:67 ../bin/apport-retrace.py:67
msgid "Path to a file with the crash database authentication information. This is used when specifying a crash ID to upload the retraced stack traces (only if neither -g, -o, nor -s are specified)"
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:69 ../bin/apport-retrace.py:69
msgid "Display retraced stack traces and ask for confirmation before sending them to the crash database."
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:71 ../bin/apport-retrace.py:71
msgid "Path to the duplicate sqlite database (default: no duplicate checking)"
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:73 ../bin/apport-retrace.py:73
msgid "Do not add StacktraceSource to the report."
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:82 ../bin/apport-retrace.py:82
msgid "You cannot use -C without -S. Stopping."
msgstr ""

#. translators: don't translate y/n, apport currently only checks for "y"
#: ../debian/tmp/usr/bin/apport-retrace.py:115 ../bin/apport-retrace.py:115
msgid "OK to send these as attachments? [y/n]"
msgstr ""

#: ../debian/tmp/usr/bin/apport-cli.py:80 ../bin/apport-cli.py:80
msgid "Press any key to continue..."
msgstr ""

#: ../debian/tmp/usr/bin/apport-cli.py:87 ../bin/apport-cli.py:87
msgid "What would you like to do? Your options are:"
msgstr ""

#: ../debian/tmp/usr/bin/apport-cli.py:100 ../bin/apport-cli.py:100
#, python-format
msgid "Please choose (%s):"
msgstr ""

#: ../debian/tmp/usr/bin/apport-cli.py:164 ../bin/apport-cli.py:164
#, python-format
msgid "(%i bytes)"
msgstr ""

#: ../debian/tmp/usr/bin/apport-cli.py:195 ../bin/apport-cli.py:195
msgid "After the problem report has been sent, please fill out the form in the\n"
"automatically opened web browser."
msgstr ""

#: ../debian/tmp/usr/bin/apport-cli.py:198 ../bin/apport-cli.py:198
#, python-format
msgid "&Send report (%s)"
msgstr ""

#: ../debian/tmp/usr/bin/apport-cli.py:202 ../bin/apport-cli.py:202
msgid "&Examine locally"
msgstr ""

#: ../debian/tmp/usr/bin/apport-cli.py:206 ../bin/apport-cli.py:206
msgid "&View report"
msgstr ""

#: ../debian/tmp/usr/bin/apport-cli.py:207 ../bin/apport-cli.py:207
msgid "&Keep report file for sending later or copying to somewhere else"
msgstr ""

#: ../debian/tmp/usr/bin/apport-cli.py:208 ../bin/apport-cli.py:208
msgid "Cancel and &ignore future crashes of this program version"
msgstr ""

#: ../debian/tmp/usr/bin/apport-cli.py:210
#: ../debian/tmp/usr/bin/apport-cli.py:287
#: ../debian/tmp/usr/bin/apport-cli.py:319
#: ../debian/tmp/usr/bin/apport-cli.py:340 ../bin/apport-cli.py:210
#: ../bin/apport-cli.py:287 ../bin/apport-cli.py:319 ../bin/apport-cli.py:340
msgid "&Cancel"
msgstr ""

#: ../debian/tmp/usr/bin/apport-cli.py:238 ../bin/apport-cli.py:238
msgid "Problem report file:"
msgstr ""

#: ../debian/tmp/usr/bin/apport-cli.py:244
#: ../debian/tmp/usr/bin/apport-cli.py:249 ../bin/apport-cli.py:244
#: ../bin/apport-cli.py:249
msgid "&Confirm"
msgstr ""

#: ../debian/tmp/usr/bin/apport-cli.py:248 ../bin/apport-cli.py:248
#, python-format
msgid "Error: %s"
msgstr ""

#: ../debian/tmp/usr/bin/apport-cli.py:255 ../bin/apport-cli.py:255
msgid "The collected information can be sent to the developers to improve the\n"
"application. This might take a few minutes."
msgstr ""

#: ../debian/tmp/usr/bin/apport-cli.py:268 ../bin/apport-cli.py:268
msgid "The collected information is being sent to the bug tracking system.\n"
"This might take a few minutes."
msgstr ""

#: ../debian/tmp/usr/bin/apport-cli.py:318 ../bin/apport-cli.py:318
msgid "&Done"
msgstr ""

#: ../debian/tmp/usr/bin/apport-cli.py:324 ../bin/apport-cli.py:324
msgid "none"
msgstr ""

#: ../debian/tmp/usr/bin/apport-cli.py:325 ../bin/apport-cli.py:325
#, python-format
msgid "Selected: %s. Multiple choices:"
msgstr ""

#: ../debian/tmp/usr/bin/apport-cli.py:341 ../bin/apport-cli.py:341
msgid "Choices:"
msgstr ""

#: ../debian/tmp/usr/bin/apport-cli.py:355 ../bin/apport-cli.py:355
msgid "Path to file (Enter to cancel):"
msgstr ""

#: ../debian/tmp/usr/bin/apport-cli.py:361 ../bin/apport-cli.py:361
msgid "File does not exist."
msgstr ""

#: ../debian/tmp/usr/bin/apport-cli.py:363 ../bin/apport-cli.py:363
msgid "This is a directory."
msgstr ""

#: ../debian/tmp/usr/bin/apport-cli.py:369 ../bin/apport-cli.py:369
msgid "To continue, you must visit the following URL:"
msgstr ""

#: ../debian/tmp/usr/bin/apport-cli.py:371 ../bin/apport-cli.py:371
msgid "You can launch a browser now, or copy this URL into a browser on another computer."
msgstr ""

#: ../debian/tmp/usr/bin/apport-cli.py:373 ../bin/apport-cli.py:373
msgid "Launch a browser now"
msgstr ""

#: ../debian/tmp/usr/bin/apport-cli.py:388 ../bin/apport-cli.py:388
msgid "No pending crash reports. Try --help for more information."
msgstr ""

#: ../bin/apport-valgrind.py:37 ../debian/tmp/usr/bin/apport-valgrind.py:37
msgid "See man page for details."
msgstr ""

#: ../bin/apport-valgrind.py:43 ../debian/tmp/usr/bin/apport-valgrind.py:43
msgid "specify the log file name produced by valgrind"
msgstr ""

#: ../bin/apport-valgrind.py:46 ../debian/tmp/usr/bin/apport-valgrind.py:46
msgid "reuse a previously created sandbox dir (SDIR) or, if it does not exist, create it"
msgstr ""

#: ../bin/apport-valgrind.py:50 ../debian/tmp/usr/bin/apport-valgrind.py:50
msgid "do  not  create  or reuse a sandbox directory for additional debug symbols but rely only on installed debug symbols."
msgstr ""

#: ../bin/apport-valgrind.py:54 ../debian/tmp/usr/bin/apport-valgrind.py:54
msgid "reuse a previously created cache dir (CDIR) or, if it does not exist, create it"
msgstr ""

#: ../bin/apport-valgrind.py:58 ../debian/tmp/usr/bin/apport-valgrind.py:58
msgid "report download/install progress when installing packages into sandbox"
msgstr ""

#: ../bin/apport-valgrind.py:62 ../debian/tmp/usr/bin/apport-valgrind.py:62
msgid "the executable that is run under valgrind's memcheck tool  for memory leak detection"
msgstr ""

#: ../bin/apport-valgrind.py:97 ../debian/tmp/usr/bin/apport-valgrind.py:97
#, python-format
msgid "Error: %s is not an executable. Stopping."
msgstr ""

#: ../gtk/apport-gtk.ui.h:2 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:2
msgid "Cancel"
msgstr ""

#: ../gtk/apport-gtk.ui.h:3 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:3
msgid "OK"
msgstr ""

#: ../gtk/apport-gtk.ui.h:4 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:4
msgid "Crash report"
msgstr ""

#: ../gtk/apport-gtk.ui.h:5 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:5
msgid "<big><b>Sorry, an internal error happened.</b></big>"
msgstr ""

#: ../gtk/apport-gtk.ui.h:8 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:8
msgid "Remember this in future"
msgstr ""

#: ../gtk/apport-gtk.ui.h:9 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:9
msgid "Ignore future problems of this program version"
msgstr ""

#: ../gtk/apport-gtk.ui.h:10 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:10
msgid "Relaunch this application"
msgstr ""

#: ../gtk/apport-gtk.ui.h:12 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:12
msgid "_Examine locally"
msgstr ""

#: ../gtk/apport-gtk.ui.h:13 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:13
msgid "Don't send"
msgstr ""

#: ../gtk/apport-gtk.ui.h:15 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:15
msgid "<big><b>Collecting problem information</b></big>"
msgstr ""

#: ../gtk/apport-gtk.ui.h:16 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:16
msgid "Information is being collected that may help the developers fix the problem you report."
msgstr ""

#: ../gtk/apport-gtk.ui.h:18 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:18
msgid "<big><b>Uploading problem information</b></big>"
msgstr ""

#: ../bin/apport-unpack.py:22 ../debian/tmp/usr/bin/apport-unpack.py:22
#, python-format
msgid "Usage: %s <report> <target directory>"
msgstr ""

#: ../bin/apport-unpack.py:47 ../debian/tmp/usr/bin/apport-unpack.py:47
msgid "Destination directory exists and is not empty."
msgstr ""

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:144
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:144
#: ../apport/ui.py:144
msgid "This package does not seem to be installed correctly"
msgstr ""

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:149
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:149
#: ../apport/ui.py:149
#, python-format
msgid "This is not an official %s package. Please remove any third party package and try again."
msgstr ""

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:166
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:166
#: ../apport/ui.py:166
#, python-format
msgid "You have some obsolete package versions installed. Please upgrade the following packages and check if the problem still occurs:\n\n"
"%s"
msgstr ""

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:299
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:299
#: ../apport/ui.py:299
msgid "unknown program"
msgstr ""

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:300
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:300
#: ../apport/ui.py:300
#, python-format
msgid "Sorry, the program \"%s\" closed unexpectedly"
msgstr ""

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:302
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1402
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:302
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1402
#: ../apport/ui.py:302 ../apport/ui.py:1402
#, python-format
msgid "Problem in %s"
msgstr ""

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:303
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:303
#: ../apport/ui.py:303
msgid "Your computer does not have enough free memory to automatically analyze the problem and send a report to the developers."
msgstr ""

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:358
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:366
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:493
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:496
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:696
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1208
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1374
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1378
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:358
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:366
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:493
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:496
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:696
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1208
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1374
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1378
#: ../apport/ui.py:358 ../apport/ui.py:366 ../apport/ui.py:493
#: ../apport/ui.py:496 ../apport/ui.py:696 ../apport/ui.py:1208
#: ../apport/ui.py:1374 ../apport/ui.py:1378
msgid "Invalid problem report"
msgstr ""

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:359
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:359
#: ../apport/ui.py:359
msgid "You are not allowed to access this problem report."
msgstr ""

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:362
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:362
#: ../apport/ui.py:362
msgid "Error"
msgstr ""

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:363
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:363
#: ../apport/ui.py:363
msgid "There is not enough disk space available to process this report."
msgstr ""

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:474
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:474
#: ../apport/ui.py:474
msgid "Invalid PID"
msgstr ""

#: ../apport/ui.py:402
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:402
msgid "The specified process ID does not exist."
msgstr ""

#: ../apport/ui.py:405
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:405
msgid "Not your PID"
msgstr ""

#: ../apport/ui.py:406
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:406
msgid "The specified process ID does not belong to you."
msgstr ""

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:447
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:447
#: ../apport/ui.py:447
msgid "No package specified"
msgstr ""

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:448
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:448
#: ../apport/ui.py:448
msgid "You need to specify a package or a PID. See --help for more information."
msgstr ""

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:471
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:471
#: ../apport/ui.py:471
msgid "Permission denied"
msgstr ""

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:472
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:472
#: ../apport/ui.py:472
msgid "The specified process does not belong to you. Please run this program as the process owner or as root."
msgstr ""

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:475
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:475
#: ../apport/ui.py:475
msgid "The specified process ID does not belong to a program."
msgstr ""

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:494
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:494
#: ../apport/ui.py:494
#, python-format
msgid "Symptom script %s did not determine an affected package"
msgstr ""

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:497
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:497
#: ../apport/ui.py:497
#, python-format
msgid "Package %s does not exist"
msgstr ""

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:521
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:708
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:713
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:521
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:708
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:713
#: ../apport/ui.py:521 ../apport/ui.py:708 ../apport/ui.py:713
msgid "Cannot create report"
msgstr ""

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:536
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:582
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:598
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:536
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:582
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:598
#: ../apport/ui.py:536 ../apport/ui.py:582 ../apport/ui.py:598
msgid "Updating problem report"
msgstr ""

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:537
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:537
#: ../apport/ui.py:537
msgid "You are not the reporter or subscriber of this problem report, or the report is a duplicate or already closed.\n\n"
"Please create a new report using \"apport-bug\"."
msgstr ""

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:546
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:546
#: ../apport/ui.py:546
msgid "You are not the reporter of this problem report. It is much easier to mark a bug as a duplicate of another than to move your comments and attachments to a new bug.\n\n"
"Subsequently, we recommend that you file a new bug report using \"apport-bug\" and make a comment in this bug about the one you file.\n\n"
"Do you really want to proceed?"
msgstr ""

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:583
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:599
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:583
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:599
#: ../apport/ui.py:583 ../apport/ui.py:599
msgid "No additional information collected."
msgstr ""

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:650
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:650
#: ../apport/ui.py:650
msgid "What kind of problem do you want to report?"
msgstr ""

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:667
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:667
#: ../apport/ui.py:667
msgid "Unknown symptom"
msgstr ""

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:668
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:668
#: ../apport/ui.py:668
#, python-format
msgid "The symptom \"%s\" is not known."
msgstr ""

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:699
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:699
#: ../apport/ui.py:699
msgid "After closing this message please click on an application window to report a problem about it."
msgstr ""

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:709
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:714
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:709
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:714
#: ../apport/ui.py:709 ../apport/ui.py:714
msgid "xprop failed to determine process ID of the window"
msgstr ""

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:728
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:728
#: ../apport/ui.py:728
msgid "%prog <report number>"
msgstr ""

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:730
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:730
#: ../apport/ui.py:730
msgid "Specify package name."
msgstr ""

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:732
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:783
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:732
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:783
#: ../apport/ui.py:732 ../apport/ui.py:783
msgid "Add an extra tag to the report. Can be specified multiple times."
msgstr ""

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:762
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:762
#: ../apport/ui.py:762
msgid "%prog [options] [symptom|pid|package|program path|.apport/.crash file]"
msgstr ""

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:765
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:765
#: ../apport/ui.py:765
msgid "Start in bug filing mode. Requires --package and an optional --pid, or just a --pid. If neither is given, display a list of known symptoms. (Implied if a single argument is given.)"
msgstr ""

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:767
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:767
#: ../apport/ui.py:767
msgid "Click a window as a target for filing a problem report."
msgstr ""

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:769
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:769
#: ../apport/ui.py:769
msgid "Start in bug updating mode. Can take an optional --package."
msgstr ""

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:771
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:771
#: ../apport/ui.py:771
msgid "File a bug report about a symptom. (Implied if symptom name is given as only argument.)"
msgstr ""

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:773
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:773
#: ../apport/ui.py:773
msgid "Specify package name in --file-bug mode. This is optional if a --pid is specified. (Implied if package name is given as only argument.)"
msgstr ""

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:775
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:775
#: ../apport/ui.py:775
msgid "Specify a running program in --file-bug mode. If this is specified, the bug report will contain more information.  (Implied if pid is given as only argument.)"
msgstr ""

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:777
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:777
#: ../apport/ui.py:777
msgid "The provided pid is a hanging application."
msgstr ""

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:779
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:779
#: ../apport/ui.py:779
#, python-format
msgid "Report the crash from given .apport or .crash file instead of the pending ones in %s. (Implied if file is given as only argument.)"
msgstr ""

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:781
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:781
#: ../apport/ui.py:781
msgid "In bug filing mode, save the collected information into a file instead of reporting it. This file can then be reported later on from a different machine."
msgstr ""

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:785
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:785
#: ../apport/ui.py:785
msgid "Print the Apport version number."
msgstr ""

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:936
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:936
#: ../apport/ui.py:936
msgid "This will launch apport-retrace in a terminal window to examine the crash."
msgstr ""

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:937
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:937
#: ../apport/ui.py:937
msgid "Run gdb session"
msgstr ""

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:938
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:938
#: ../apport/ui.py:938
msgid "Run gdb session without downloading debug symbols"
msgstr ""

#. TRANSLATORS: %s contains the crash report file name
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:940
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:940
#: ../apport/ui.py:940
#, python-format
msgid "Update %s with fully symbolic stack trace"
msgstr ""

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:976
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:976
#: ../apport/ui.py:976
msgid "Can't remember send report status settings"
msgstr ""

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:977
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:977
#: ../apport/ui.py:977
msgid "Saving crash reporting state failed. Can't set auto or never reporting mode."
msgstr ""

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1036
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1046
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1036
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1046
#: ../apport/ui.py:1036 ../apport/ui.py:1046
msgid "This problem report applies to a program which is not installed any more."
msgstr ""

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1061
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1061
#: ../apport/ui.py:1061
#, python-format
msgid "The problem happened with the program %s which changed since the crash occurred."
msgstr ""

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1108
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1165
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1380
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1108
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1165
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1380
#: ../apport/ui.py:1108 ../apport/ui.py:1165 ../apport/ui.py:1380
msgid "This problem report is damaged and cannot be processed."
msgstr ""

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1116
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1116
#: ../apport/ui.py:1116
#, python-format
msgid "This report is about a snap published by %s. Contact them via %s for help."
msgstr ""

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1119
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1119
#: ../apport/ui.py:1119
#, python-format
msgid "This report is about a snap published by %s. No contact address has been provided; visit the forum at https://forum.snapcraft.io/ for help."
msgstr ""

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1123
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1123
#: ../apport/ui.py:1123
msgid "This report is about a package that is not installed."
msgstr ""

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1127
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1127
#: ../apport/ui.py:1127
msgid "An error occurred while attempting to process this problem report:"
msgstr ""

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1134
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1134
#: ../apport/ui.py:1134
#, python-format
msgid "You are about to report a bug against the deb package, but you also a have snap published by %s installed. You can contact them via %s for help. Do you want to continue with the bug report against the deb?"
msgstr ""

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1136
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1136
#: ../apport/ui.py:1136
#, python-format
msgid "You are about to report a bug against the deb package, but you also a have snap published by %s installed. For the snap, no contact address has been provided; visit the forum at https://forum.snapcraft.io/ for help. Do you want to continue with the bug report against the deb?"
msgstr ""

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1209
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1209
#: ../apport/ui.py:1209
msgid "Could not determine the package or source package name."
msgstr ""

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1227
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1227
#: ../apport/ui.py:1227
msgid "Unable to start web browser"
msgstr ""

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1228
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1228
#: ../apport/ui.py:1228
#, python-format
msgid "Unable to start web browser to open %s."
msgstr ""

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1328
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1328
#: ../apport/ui.py:1328
#, python-format
msgid "Please enter your account information for the %s bug tracking system"
msgstr ""

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1340
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1340
#: ../apport/ui.py:1340
msgid "Network problem"
msgstr ""

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1342
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1342
#: ../apport/ui.py:1342
msgid "Cannot connect to crash database, please check your Internet connection."
msgstr ""

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1369
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1369
#: ../apport/ui.py:1369
msgid "Memory exhaustion"
msgstr ""

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1370
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1370
#: ../apport/ui.py:1370
msgid "Your system does not have enough memory to process this crash report."
msgstr ""

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1405
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1405
#: ../apport/ui.py:1405
#, python-format
msgid "The problem cannot be reported:\n\n"
"%s"
msgstr ""

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1461
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1468
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1461
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1468
#: ../apport/ui.py:1461 ../apport/ui.py:1468
msgid "Problem already known"
msgstr ""

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1462
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1462
#: ../apport/ui.py:1462
msgid "This problem was already reported in the bug report displayed in the web browser. Please check if you can add any further information that might be helpful for the developers."
msgstr ""

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1469
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1469
#: ../apport/ui.py:1469
msgid "This problem was already reported to developers. Thank you!"
msgstr ""

#: ../data/apportcheckresume.py:67
#: ../debian/tmp/usr/share/apport/apportcheckresume.py:67
msgid "This occurred during a previous suspend, and prevented the system from resuming properly."
msgstr ""

#: ../data/apportcheckresume.py:69
#: ../debian/tmp/usr/share/apport/apportcheckresume.py:69
msgid "This occurred during a previous hibernation, and prevented the system from resuming properly."
msgstr ""

#: ../data/apportcheckresume.py:74
#: ../debian/tmp/usr/share/apport/apportcheckresume.py:74
msgid "The resume processing hung very near the end and will have appeared to have completed normally."
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.py:161 ../gtk/apport-gtk.py:161
#, python-format
msgid "Sorry, the application %s has stopped unexpectedly."
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.py:164 ../gtk/apport-gtk.py:164
#, python-format
msgid "Sorry, %s has closed unexpectedly."
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.py:239 ../gtk/apport-gtk.py:239
#, python-format
msgid "The application %s has stopped responding."
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.py:243 ../gtk/apport-gtk.py:243
#, python-format
msgid "The program \"%s\" has stopped responding."
msgstr ""

