# Russian translation for apport
# Copyright (c) (c) 2006 Canonical Ltd, and Rosetta Contributors 2006
# This file is distributed under the same license as the apport package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2006.
#
msgid ""
msgstr ""
"Project-Id-Version: apport\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2020-07-02 10:22+0000\n"
"PO-Revision-Date: 2019-09-11 18:21+0000\n"
"Last-Translator: Eugene Roskin <Unknown>\n"
"Language-Team: Russian <ru@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Launchpad-Export-Date: 2020-07-09 18:27+0000\n"
"X-Generator: Launchpad (build 4809fcb62f445aaa3ae919f7f6c3cc7d156ea57a)\n"
"Language: ru\n"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:139
#: ../apport/ui.py:139
msgid "This package does not seem to be installed correctly"
msgstr "Возможно, этот пакет установлен неправильно"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:144
#: ../apport/ui.py:144
#, python-format
msgid ""
"This is not an official %s package. Please remove any third party package "
"and try again."
msgstr ""
"Этот пакет не является официальным пакетом %s. Пожалуйста, удалите все "
"сторонние пакеты и попробуйте снова."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:163
#: ../apport/ui.py:163
#, python-format
msgid ""
"You have some obsolete package versions installed. Please upgrade the "
"following packages and check if the problem still occurs:\n"
"\n"
"%s"
msgstr ""
"В вашей системе установлены устаревшие версии некоторых пакетов. Обновите "
"следующие пакеты и проверьте, осталась ли проблема:\n"
"\n"
"%s"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:300
#: ../apport/ui.py:300
msgid "unknown program"
msgstr "неизвестная программа"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:301
#: ../apport/ui.py:301
#, python-format
msgid "Sorry, the program \"%s\" closed unexpectedly"
msgstr "Извините, программа %s аварийно завершила свою работу"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:303
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1449
#: ../apport/ui.py:303 ../apport/ui.py:1449
#, python-format
msgid "Problem in %s"
msgstr "Неполадка в %s"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:304
#: ../apport/ui.py:304
msgid ""
"Your computer does not have enough free memory to automatically analyze the "
"problem and send a report to the developers."
msgstr ""
"В вашем компьютере недостаточно свободной памяти, чтобы автоматически "
"проанализировать неполадку и отправить отчет разработчикам."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:359
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:367
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:510
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:513
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:718
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1255
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1421
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1425
#: ../apport/ui.py:359 ../apport/ui.py:367 ../apport/ui.py:510
#: ../apport/ui.py:513 ../apport/ui.py:718 ../apport/ui.py:1255
#: ../apport/ui.py:1421 ../apport/ui.py:1425
msgid "Invalid problem report"
msgstr "Неверный отчёт об ошибке"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:360
#: ../apport/ui.py:360
msgid "You are not allowed to access this problem report."
msgstr "У вас нет доступа к отчёту о неполадке."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:363
#: ../apport/ui.py:363
msgid "Error"
msgstr "Ошибка"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:364
#: ../apport/ui.py:364
msgid "There is not enough disk space available to process this report."
msgstr "Недостаточно места на диске для обработки этого отчёта."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:402
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:491
#: ../apport/ui.py:402 ../apport/ui.py:491
msgid "Invalid PID"
msgstr "Неверный PID"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:403
#: ../apport/ui.py:403
msgid "The specified process ID does not exist."
msgstr "Указанный ID процесса не существует."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:406
#: ../apport/ui.py:406
msgid "Not your PID"
msgstr "Не ваш PID"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:407
#: ../apport/ui.py:407
msgid "The specified process ID does not belong to you."
msgstr "Указанный ID процесса не принадлежит вам."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:458
#: ../apport/ui.py:458
msgid "No package specified"
msgstr "Не указан пакет"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:459
#: ../apport/ui.py:459
msgid ""
"You need to specify a package or a PID. See --help for more information."
msgstr ""
"Необходимо указать пакет или PID. Запустите программу с ключом --help для "
"получения дополнительной информации."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:488
#: ../apport/ui.py:488
msgid "Permission denied"
msgstr "В доступе отказано"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:489
#: ../apport/ui.py:489
msgid ""
"The specified process does not belong to you. Please run this program as the "
"process owner or as root."
msgstr ""
"Указанный процесс запущен другим пользователем. Запустите эту программу с "
"правами владельца процесса или администратора системы."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:492
#: ../apport/ui.py:492
msgid "The specified process ID does not belong to a program."
msgstr "Указанный PID принадлежит другому процессу."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:511
#: ../apport/ui.py:511
#, python-format
msgid "Symptom script %s did not determine an affected package"
msgstr "Симптоматический скрипт %s не может определить затронутый пакет"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:514
#: ../apport/ui.py:514
#, python-format
msgid "Package %s does not exist"
msgstr "Пакет %s не существует"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:543
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:730
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:735
#: ../apport/ui.py:543 ../apport/ui.py:730 ../apport/ui.py:735
msgid "Cannot create report"
msgstr "Невозможно создать отчет"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:558
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:604
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:620
#: ../apport/ui.py:558 ../apport/ui.py:604 ../apport/ui.py:620
msgid "Updating problem report"
msgstr "Обновление отчета о проблеме"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:559
#: ../apport/ui.py:559
msgid ""
"You are not the reporter or subscriber of this problem report, or the report "
"is a duplicate or already closed.\n"
"\n"
"Please create a new report using \"apport-bug\"."
msgstr ""
"Вы не являетесь отправителем или получателем отчета об этой проблеме, "
"возможно отчет уже существует или уже был закрыт."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:568
#: ../apport/ui.py:568
msgid ""
"You are not the reporter of this problem report. It is much easier to mark a "
"bug as a duplicate of another than to move your comments and attachments to "
"a new bug.\n"
"\n"
"Subsequently, we recommend that you file a new bug report using \"apport-"
"bug\" and make a comment in this bug about the one you file.\n"
"\n"
"Do you really want to proceed?"
msgstr ""
"Вы не являетесь создателем данного отчета. Намного проще, отметить ошибку "
"как уже существующую, чем создавать свои комментарии и вкладывать их в новую "
"ошибку.\n"
"\n"
"Впоследствии, мы рекомендуем вам подать новое сообщение об ошибке "
"использовании \"ошибка apport\", и сделать замечание об этой ошибке в том же "
"файле.\n"
"\n"
"Вы действительно хотите продолжить?"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:605
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:621
#: ../apport/ui.py:605 ../apport/ui.py:621
msgid "No additional information collected."
msgstr "Дополнительная информация не была собрана."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:672
#: ../apport/ui.py:672
msgid "What kind of problem do you want to report?"
msgstr "О какой проблеме вы бы хотели сообщить?"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:689
#: ../apport/ui.py:689
msgid "Unknown symptom"
msgstr "Неизвестный симптом"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:690
#: ../apport/ui.py:690
#, python-format
msgid "The symptom \"%s\" is not known."
msgstr "Симптом «%s» не известен"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:721
#: ../apport/ui.py:721
msgid ""
"After closing this message please click on an application window to report a "
"problem about it."
msgstr ""
"После закрытия этого сообщения, пожалуйста, щелкните по окну приложения, "
"чтобы сообщить о проблеме."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:731
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:736
#: ../apport/ui.py:731 ../apport/ui.py:736
msgid "xprop failed to determine process ID of the window"
msgstr "xprop не удалось определить ID процесса этого окна"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:750
#: ../apport/ui.py:750
msgid "%prog <report number>"
msgstr "%prog <номер отчета>"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:752
#: ../apport/ui.py:752
msgid "Specify package name."
msgstr "Задайте имя пакета."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:754
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:805
#: ../apport/ui.py:754 ../apport/ui.py:805
msgid "Add an extra tag to the report. Can be specified multiple times."
msgstr ""
"Добавить дополнительный тег в отчет. Может быть указан несколько раз."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:784
#: ../apport/ui.py:784
msgid ""
"%prog [options] [symptom|pid|package|program path|.apport/.crash file]"
msgstr ""
"%prog [параметры] [признак|pid|пакет|путь до программы|.apport/.crash файл]"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:787
#: ../apport/ui.py:787
msgid ""
"Start in bug filing mode. Requires --package and an optional --pid, or just "
"a --pid. If neither is given, display a list of known symptoms. (Implied if "
"a single argument is given.)"
msgstr ""
"Запуск в режиме отправки отчёта об ошибке. Требует параметр --package и "
"необязательный --pid, или только --pid. Если параметры не переданы, "
"отображает список известных симптомов. (Применяется, когда передан "
"единственный аргумент.)"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:789
#: ../apport/ui.py:789
msgid "Click a window as a target for filing a problem report."
msgstr "Щелкните по целевому окну для заполнения отчёта о проблеме."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:791
#: ../apport/ui.py:791
msgid "Start in bug updating mode. Can take an optional --package."
msgstr ""
"Запустить в режиме обновления ошибки. Может принимать дополнительный ключ --"
"package."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:793
#: ../apport/ui.py:793
msgid ""
"File a bug report about a symptom. (Implied if symptom name is given as only "
"argument.)"
msgstr ""
"Отправить отчёт об ошибке с симптомом. (Применяется, когда название симптома "
"передано в качестве единственного параметра.)"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:795
#: ../apport/ui.py:795
msgid ""
"Specify package name in --file-bug mode. This is optional if a --pid is "
"specified. (Implied if package name is given as only argument.)"
msgstr ""
"Указать имя пакета в режиме --file-bug. Необязательно, если указан --pid. "
"(Применяется, когда имя пакета передано в качестве единственного параметра.)"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:797
#: ../apport/ui.py:797
msgid ""
"Specify a running program in --file-bug mode. If this is specified, the bug "
"report will contain more information.  (Implied if pid is given as only "
"argument.)"
msgstr ""
"Указывает запущенную программу при работе в режиме --file-bug. При этом "
"отчет будет содержать больше информации. (Подразумевается, что pid — "
"единственный указанный аргумент.)"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:799
#: ../apport/ui.py:799
msgid "The provided pid is a hanging application."
msgstr "Указанный идентификатор принадлежит процессу, который не отвечает."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:801
#: ../apport/ui.py:801
#, python-format
msgid ""
"Report the crash from given .apport or .crash file instead of the pending "
"ones in %s. (Implied if file is given as only argument.)"
msgstr ""
"Отправить данные о сбое из заданного файла .apport или .crash вместо "
"ожидаемых в %s. (Применяется, когда файл передан в качестве единственного "
"параметра.)"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:803
#: ../apport/ui.py:803
msgid ""
"In bug filing mode, save the collected information into a file instead of "
"reporting it. This file can then be reported later on from a different "
"machine."
msgstr ""
"При работе в режиме отправки отчета, сохраняет информацию в файле вместо ее "
"отправки. Этот файл можно будет отправить позднее или с другого компьютера."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:807
#: ../apport/ui.py:807
msgid "Print the Apport version number."
msgstr "Напечатать номер версии Apport."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:958
#: ../apport/ui.py:958
msgid ""
"This will launch apport-retrace in a terminal window to examine the crash."
msgstr ""
"Будет произведён запуск «apport-retrace» в окне терминала для выполнения "
"проверки аварийного завершения работы."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:959
#: ../apport/ui.py:959
msgid "Run gdb session"
msgstr "Запустить сеанс gdb"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:960
#: ../apport/ui.py:960
msgid "Run gdb session without downloading debug symbols"
msgstr "Запустить сеанс gdb, не выполняя загрузку отладочных символов"

#. TRANSLATORS: %s contains the crash report file name
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:962
#: ../apport/ui.py:962
#, python-format
msgid "Update %s with fully symbolic stack trace"
msgstr "Обновить %s с полным отслеживанием символического стека"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:998
#: ../apport/ui.py:998
msgid "Can't remember send report status settings"
msgstr "Не удаётся запомнить настройки статуса отправки отчёта"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:999
#: ../apport/ui.py:999
msgid ""
"Saving crash reporting state failed. Can't set auto or never reporting mode."
msgstr ""
"Не удалось сохранить состояние отчета о сбое. Не удается установить режим "
"авто или никогда."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1058
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1068
#: ../apport/ui.py:1058 ../apport/ui.py:1068
msgid ""
"This problem report applies to a program which is not installed any more."
msgstr "Этот отчет о проблеме относится к программе, которая не установлена."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1083
#: ../apport/ui.py:1083
#, python-format
msgid ""
"The problem happened with the program %s which changed since the crash "
"occurred."
msgstr ""
"Неполадка произошла с программой %s, в которую были внесены изменения с "
"момента её аварийного завершения работы."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1130
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1211
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1427
#: ../apport/ui.py:1130 ../apport/ui.py:1211 ../apport/ui.py:1427
msgid "This problem report is damaged and cannot be processed."
msgstr "Этот отчёт о неполадке повреждён и не может быть обработан."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1135
#: ../apport/ui.py:1135
msgid "This report is about a package that is not installed."
msgstr "Это отчёт о пакете, который не установлен."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1139
#: ../apport/ui.py:1139
msgid "An error occurred while attempting to process this problem report:"
msgstr "Произошла ошибка при попытке обработать это сообщение о неполадке:"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1149
#: ../apport/ui.py:1149
msgid ""
"You have two versions of this application installed, which one do you want "
"to report a bug against?"
msgstr ""

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1150
#: ../apport/ui.py:1150
#, python-format
msgid "%s snap"
msgstr ""

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1151
#: ../apport/ui.py:1151
#, python-format
msgid "%s deb package"
msgstr ""

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1184
#: ../apport/ui.py:1184
#, python-format
msgid ""
"%s is provided by a snap published by %s. Contact them via %s for help."
msgstr ""

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1186
#: ../apport/ui.py:1186
#, python-format
msgid ""
"%s is provided by a snap published by %s. No contact address has been "
"provided; visit the forum at https://forum.snapcraft.io/ for help."
msgstr ""

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1256
#: ../apport/ui.py:1256
msgid "Could not determine the package or source package name."
msgstr "Не удалось определить имя пакета или имя пакета с исходным кодом."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1274
#: ../apport/ui.py:1274
msgid "Unable to start web browser"
msgstr "Не удалось запустить веб-браузер"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1275
#: ../apport/ui.py:1275
#, python-format
msgid "Unable to start web browser to open %s."
msgstr "Не удалось запустить веб-браузер, чтобы открыть %s."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1375
#: ../apport/ui.py:1375
#, python-format
msgid "Please enter your account information for the %s bug tracking system"
msgstr ""
"Пожалуйста, введите данные вашей учетной записи в системе учёта ошибок %s"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1387
#: ../apport/ui.py:1387
msgid "Network problem"
msgstr "Неполадка с сетью"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1389
#: ../apport/ui.py:1389
msgid ""
"Cannot connect to crash database, please check your Internet connection."
msgstr ""
"Не удается подключиться к базе данных по сбоям, пожалуйста, проверьте "
"подключение к Интернету."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1416
#: ../apport/ui.py:1416
msgid "Memory exhaustion"
msgstr "Недостаток памяти"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1417
#: ../apport/ui.py:1417
msgid "Your system does not have enough memory to process this crash report."
msgstr "В системе недостаточно памяти для обработки этого отчёта об ошибке."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1452
#: ../apport/ui.py:1452
#, python-format
msgid ""
"The problem cannot be reported:\n"
"\n"
"%s"
msgstr ""
"Не удаётся сообщить о неполадке:\n"
"\n"
"%s"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1508
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1515
#: ../apport/ui.py:1508 ../apport/ui.py:1515
msgid "Problem already known"
msgstr "О неполадке уже известно"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1509
#: ../apport/ui.py:1509
msgid ""
"This problem was already reported in the bug report displayed in the web "
"browser. Please check if you can add any further information that might be "
"helpful for the developers."
msgstr ""
"Об этой неполадке уже известно. Существующий отчёт о ней открыт в вашем "
"браузере. Пожалуйста, проверьте, можете ли вы добавить в него иную полезную "
"информацию, которая могла бы помочь разработчикам."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1516
#: ../apport/ui.py:1516
msgid "This problem was already reported to developers. Thank you!"
msgstr ""
"Сообщение о неисправности отправлено разработчикам. Спасибо за помощь!"

#: ../debian/tmp/usr/bin/apport-unpack.py:22 ../bin/apport-unpack.py:22
#, python-format
msgid "Usage: %s <report> <target directory>"
msgstr "Использование: %s <отчет> <папка назначения>"

#: ../debian/tmp/usr/bin/apport-unpack.py:42 ../bin/apport-unpack.py:42
msgid "Destination directory exists and is not empty."
msgstr "Папка назначения существует и не пуста."

#: ../debian/tmp/usr/share/apport/apport-kde.py:186 ../gtk/apport-gtk.ui.h:6
#: ../debian/tmp/usr/bin/apport-cli.py:194 ../bin/apport-cli.py:194
#: ../kde/apport-kde.py:186 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:6
#: ../debian/tmp/usr/share/apport/apport-gtk.py:181 ../gtk/apport-gtk.py:181
msgid "Send problem report to the developers?"
msgstr "Отправить отчёт об ошибке разработчикам?"

#: ../debian/tmp/usr/share/apport/apport-kde.py:194 ../gtk/apport-gtk.ui.h:14
#: ../kde/apport-kde.py:194 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:14
#: ../debian/tmp/usr/share/apport/apport-gtk.py:188 ../gtk/apport-gtk.py:188
msgid "Send"
msgstr "Отправить"

#: ../debian/tmp/usr/share/apport/apport-kde.py:200
#: ../debian/tmp/usr/share/apport/apport-kde.py:238 ../kde/apport-kde.py:200
#: ../kde/apport-kde.py:238 ../debian/tmp/usr/share/apport/apport-gtk.py:169
#: ../gtk/apport-gtk.py:169
#, python-format
msgid "Sorry, %s has experienced an internal error."
msgstr "Извините, возникла внутренняя ошибка %s."

#: ../debian/tmp/usr/share/apport/apport-kde.py:208 ../kde/apport-kde.py:208
#: ../debian/tmp/usr/share/apport/apport-gtk.py:259 ../gtk/apport-gtk.py:259
#, python-format
msgid "Package: %s"
msgstr "Пакет: %s"

#: ../debian/tmp/usr/share/apport/apport-kde.py:214 ../kde/apport-kde.py:214
#: ../debian/tmp/usr/share/apport/apport-gtk.py:265 ../gtk/apport-gtk.py:265
msgid "Sorry, a problem occurred while installing software."
msgstr ""
"Извините, обнаружена неполадка во время установки программного обеспечения."

#: ../debian/tmp/usr/share/apport/apport-kde.py:220 ../kde/apport-kde.py:220
#: ../debian/tmp/usr/share/apport/apport-gtk.py:274
#: ../debian/tmp/usr/share/apport/apport-gtk.py:289 ../gtk/apport-gtk.py:274
#: ../gtk/apport-gtk.py:289
#, python-format
msgid "The application %s has experienced an internal error."
msgstr "В приложении %s произошла внутренняя ошибка."

#: ../debian/tmp/usr/share/apport/apport-kde.py:223 ../kde/apport-kde.py:223
#: ../debian/tmp/usr/share/apport/apport-gtk.py:277 ../gtk/apport-gtk.py:277
#, python-format
msgid "The application %s has closed unexpectedly."
msgstr "Приложение %s внезапно закрылось."

#: ../debian/tmp/usr/share/apport/apport-kde.py:231
#: ../debian/tmp/usr/share/apport/apport-kde.py:244 ../kde/apport-kde.py:231
#: ../kde/apport-kde.py:244 ../debian/tmp/usr/share/apport/apport-gtk.py:216
#: ../gtk/apport-gtk.py:216
msgid "Continue"
msgstr "Продолжить"

#: ../debian/tmp/usr/share/apport/apport-kde.py:234 ../kde/apport-kde.py:234
msgid "Leave Closed"
msgstr "Оставить закрытым"

#: ../debian/tmp/usr/share/apport/apport-kde.py:235
#: ../debian/tmp/usr/share/apport/apport-kde.py:381 ../kde/apport-kde.py:235
#: ../kde/apport-kde.py:381
msgid "Relaunch"
msgstr "Перезапустить"

#: ../debian/tmp/usr/share/apport/apport-kde.py:241 ../gtk/apport-gtk.ui.h:7
#: ../kde/apport-kde.py:241 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:7
#: ../debian/tmp/usr/share/apport/apport-gtk.py:297 ../gtk/apport-gtk.py:297
msgid "If you notice further problems, try restarting the computer."
msgstr ""
"При возникновении этой неполадки в дальнейшем попробуйте перезапустить "
"компьютер."

#: ../debian/tmp/usr/share/apport/apport-kde.py:245 ../kde/apport-kde.py:245
#: ../debian/tmp/usr/share/apport/apport-gtk.py:299 ../gtk/apport-gtk.py:299
msgid "Ignore future problems of this type"
msgstr "Игнорировать этот тип неполадок в дальнейшем"

#: ../debian/tmp/usr/share/apport/apport-kde.py:289 ../kde/apport-kde.py:289
#: ../debian/tmp/usr/share/apport/apport-gtk.py:579 ../gtk/apport-gtk.py:579
msgid "Hide Details"
msgstr "Скрыть подробности"

#: ../debian/tmp/usr/share/apport/apport-kde.py:292 ../gtk/apport-gtk.ui.h:11
#: ../kde/apport-kde.py:292 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:11
#: ../debian/tmp/usr/share/apport/apport-gtk.py:204
#: ../debian/tmp/usr/share/apport/apport-gtk.py:575 ../gtk/apport-gtk.py:204
#: ../gtk/apport-gtk.py:575
msgid "Show Details"
msgstr "Показать подробности"

#: ../debian/tmp/usr/share/apport/apport-kde.py:315 ../kde/apport-kde.py:315
msgid "Username:"
msgstr "Имя пользователя:"

#: ../debian/tmp/usr/share/apport/apport-kde.py:316 ../kde/apport-kde.py:316
msgid "Password:"
msgstr "Пароль:"

#: ../debian/tmp/usr/share/apport/apport-kde.py:363
#: ../debian/tmp/usr/bin/apport-cli.py:166 ../bin/apport-cli.py:166
#: ../kde/apport-kde.py:363 ../debian/tmp/usr/share/apport/apport-gtk.py:146
#: ../gtk/apport-gtk.py:146
msgid "(binary data)"
msgstr "(двоичные данные)"

#: ../debian/tmp/usr/share/apport/apport-kde.py:406 ../kde/apport-kde.py:406
msgid "Collecting Problem Information"
msgstr "Сбор информации о неполадке"

#: ../debian/tmp/usr/share/apport/apport-kde.py:407
#: ../debian/tmp/usr/bin/apport-cli.py:254 ../bin/apport-cli.py:254
#: ../kde/apport-kde.py:407
msgid "Collecting problem information"
msgstr "Сбор информации о проблеме"

#: ../debian/tmp/usr/share/apport/apport-kde.py:408 ../kde/apport-kde.py:408
msgid ""
"The collected information can be sent to the developers to improve the "
"application. This might take a few minutes."
msgstr ""
"Собранную информацию можно отправить разработчикам чтобы улучшить "
"приложение. Это может занять несколько минут."

#: ../debian/tmp/usr/share/apport/apport-kde.py:434 ../kde/apport-kde.py:434
msgid "Uploading Problem Information"
msgstr "Передача информации о неполадке"

#: ../debian/tmp/usr/share/apport/apport-kde.py:435 ../gtk/apport-gtk.ui.h:17
#: ../debian/tmp/usr/bin/apport-cli.py:267 ../bin/apport-cli.py:267
#: ../kde/apport-kde.py:435 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:17
msgid "Uploading problem information"
msgstr "Передача информации о неполадке"

#: ../debian/tmp/usr/share/apport/apport-kde.py:436 ../gtk/apport-gtk.ui.h:19
#: ../kde/apport-kde.py:436 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:19
msgid ""
"The collected information is being sent to the bug tracking system. This "
"might take a few minutes."
msgstr ""
"Собранные данные пересылаются в систему учёта ошибок. Это может занять "
"несколько минут."

#: ../debian/tmp/usr/share/apport/apport-kde.py:469
#: ../debian/tmp/usr/share/apport/apport-kde.py:504
#: ../debian/tmp/usr/share/apport/apport-kde.py:524 ../gtk/apport-gtk.ui.h:1
#: ../kde/apport-kde.py:469 ../kde/apport-kde.py:504 ../kde/apport-kde.py:524
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:1
msgid "Apport"
msgstr "Apport"

#: ../gtk/apport-gtk.ui.h:2 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:2
msgid "Cancel"
msgstr "Отмена"

#: ../gtk/apport-gtk.ui.h:3 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:3
msgid "OK"
msgstr "OK"

#: ../gtk/apport-gtk.ui.h:4 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:4
msgid "Crash report"
msgstr "Отчёт о неполадке"

#: ../gtk/apport-gtk.ui.h:5 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:5
msgid "<big><b>Sorry, an internal error happened.</b></big>"
msgstr "<big><b>Извините, возникла внутренняя ошибка.</b></big>"

#: ../gtk/apport-gtk.ui.h:8 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:8
msgid "Remember this in future"
msgstr "Запомнить на будущее"

#: ../gtk/apport-gtk.ui.h:9 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:9
msgid "Ignore future problems of this program version"
msgstr "Игнорировать будущие сбои в этой версии программы"

#: ../gtk/apport-gtk.ui.h:10 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:10
msgid "Relaunch this application"
msgstr "Перезапустить это приложение"

#: ../gtk/apport-gtk.ui.h:12 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:12
msgid "_Examine locally"
msgstr "_Локальная проверка"

#: ../gtk/apport-gtk.ui.h:13 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:13
msgid "Don't send"
msgstr "Не отправлять"

#: ../gtk/apport-gtk.ui.h:15 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:15
msgid "<big><b>Collecting problem information</b></big>"
msgstr "<big><b>Сбор информации о неполадке</b></big>"

#: ../gtk/apport-gtk.ui.h:16 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:16
msgid ""
"Information is being collected that may help the developers fix the problem "
"you report."
msgstr ""
"Производится сбор информации, которая может помочь разработчикам исправить "
"эту ошибку."

#: ../gtk/apport-gtk.ui.h:18 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:18
msgid "<big><b>Uploading problem information</b></big>"
msgstr "<big><b>Передача сведений о неполадке</b></big>"

#: ../bin/apport-valgrind.py:37 ../debian/tmp/usr/bin/apport-valgrind.py:37
msgid "See man page for details."
msgstr "Смотрите подробности в man-странице."

#: ../bin/apport-valgrind.py:43 ../debian/tmp/usr/bin/apport-valgrind.py:43
msgid "specify the log file name produced by valgrind"
msgstr "укажите имя log-файла для valgrind"

#: ../bin/apport-valgrind.py:46 ../debian/tmp/usr/bin/apport-valgrind.py:46
msgid ""
"reuse a previously created sandbox dir (SDIR) or, if it does not exist, "
"create it"
msgstr ""
"использовать ранее созданный каталог песочницы (SDIR) или создать его если "
"он не существует"

#: ../bin/apport-valgrind.py:50 ../debian/tmp/usr/bin/apport-valgrind.py:50
msgid ""
"do  not  create  or reuse a sandbox directory for additional debug symbols "
"but rely only on installed debug symbols."
msgstr ""
"не создавать и не использовать каталог песочницы для дополнительных символов "
"отладки, а полагаться лишь на установленные символы отладки."

#: ../bin/apport-valgrind.py:54 ../debian/tmp/usr/bin/apport-valgrind.py:54
msgid ""
"reuse a previously created cache dir (CDIR) or, if it does not exist, create "
"it"
msgstr ""
"использовать ранее созданный каталог кэша (CDIR) или создать его если он не "
"существует"

#: ../bin/apport-valgrind.py:58 ../debian/tmp/usr/bin/apport-valgrind.py:58
msgid ""
"report download/install progress when installing packages into sandbox"
msgstr ""
"показывать прогресс загрузки/установки во время установки пакетов в песочницу"

#: ../bin/apport-valgrind.py:62 ../debian/tmp/usr/bin/apport-valgrind.py:62
msgid ""
"the executable that is run under valgrind's memcheck tool  for memory leak "
"detection"
msgstr ""
"исполняемый файл, который запускается под контролем valgrind memcheck для "
"определения утечек памяти"

#: ../bin/apport-valgrind.py:66 ../bin/apport-retrace.py:65
#: ../debian/tmp/usr/bin/apport-valgrind.py:66
#: ../debian/tmp/usr/bin/apport-retrace.py:65
msgid ""
"Install an extra package into the sandbox (can be specified multiple times)"
msgstr ""
"Установить во временную среду дополнительный пакет (может указываться "
"несколько раз)"

#: ../bin/apport-valgrind.py:97 ../debian/tmp/usr/bin/apport-valgrind.py:97
#, python-format
msgid "Error: %s is not an executable. Stopping."
msgstr "Ошибка: %s — не исполняемый файл. Остановка."

#: ../debian/tmp/usr/bin/apport-cli.py:80 ../bin/apport-cli.py:80
msgid "Press any key to continue..."
msgstr "Чтобы продолжить, нажмите любую клавишу..."

#: ../debian/tmp/usr/bin/apport-cli.py:87 ../bin/apport-cli.py:87
msgid "What would you like to do? Your options are:"
msgstr "Что вы хотите сделать? Возможные варианты:"

#: ../debian/tmp/usr/bin/apport-cli.py:100 ../bin/apport-cli.py:100
#, python-format
msgid "Please choose (%s):"
msgstr "Пожалуйста, выберите (%s):"

#: ../debian/tmp/usr/bin/apport-cli.py:164 ../bin/apport-cli.py:164
#, python-format
msgid "(%i bytes)"
msgstr "(%i байт)"

#: ../debian/tmp/usr/bin/apport-cli.py:195 ../bin/apport-cli.py:195
msgid ""
"After the problem report has been sent, please fill out the form in the\n"
"automatically opened web browser."
msgstr ""
"После того, как отчёт будет отправлен, заполните форму\n"
"в автоматически открывшемся окне браузера."

#: ../debian/tmp/usr/bin/apport-cli.py:198 ../bin/apport-cli.py:198
#, python-format
msgid "&Send report (%s)"
msgstr "&Отправить отчёт (%s)"

#: ../debian/tmp/usr/bin/apport-cli.py:202 ../bin/apport-cli.py:202
msgid "&Examine locally"
msgstr "&Локальная проверка"

#: ../debian/tmp/usr/bin/apport-cli.py:206 ../bin/apport-cli.py:206
msgid "&View report"
msgstr "&Просмотреть отчёт"

#: ../debian/tmp/usr/bin/apport-cli.py:207 ../bin/apport-cli.py:207
msgid "&Keep report file for sending later or copying to somewhere else"
msgstr ""
"&Сохранить файл отчёта для последующей отправки или копирования куда-либо"

#: ../debian/tmp/usr/bin/apport-cli.py:208 ../bin/apport-cli.py:208
msgid "Cancel and &ignore future crashes of this program version"
msgstr "Отменить и &игнорировать будущие сбои в этой версии программы"

#: ../debian/tmp/usr/bin/apport-cli.py:210
#: ../debian/tmp/usr/bin/apport-cli.py:287
#: ../debian/tmp/usr/bin/apport-cli.py:319
#: ../debian/tmp/usr/bin/apport-cli.py:340 ../bin/apport-cli.py:210
#: ../bin/apport-cli.py:287 ../bin/apport-cli.py:319 ../bin/apport-cli.py:340
msgid "&Cancel"
msgstr "О&тменить"

#: ../debian/tmp/usr/bin/apport-cli.py:238 ../bin/apport-cli.py:238
msgid "Problem report file:"
msgstr "Файл отчёта о проблеме:"

#: ../debian/tmp/usr/bin/apport-cli.py:244
#: ../debian/tmp/usr/bin/apport-cli.py:249 ../bin/apport-cli.py:244
#: ../bin/apport-cli.py:249
msgid "&Confirm"
msgstr "&Подтвердить"

#: ../debian/tmp/usr/bin/apport-cli.py:248 ../bin/apport-cli.py:248
#, python-format
msgid "Error: %s"
msgstr "Ошибка: %s"

#: ../debian/tmp/usr/bin/apport-cli.py:255 ../bin/apport-cli.py:255
msgid ""
"The collected information can be sent to the developers to improve the\n"
"application. This might take a few minutes."
msgstr ""
"Собранная информация может быть направлена разработчикам\n"
"для улучшения приложения. Это может занять несколько минут."

#: ../debian/tmp/usr/bin/apport-cli.py:268 ../bin/apport-cli.py:268
msgid ""
"The collected information is being sent to the bug tracking system.\n"
"This might take a few minutes."
msgstr ""
"Собранная информация направляется в систему отслеживания ошибок.\n"
"Это может занять несколько минут."

#: ../debian/tmp/usr/bin/apport-cli.py:318 ../bin/apport-cli.py:318
msgid "&Done"
msgstr "&Готово"

#: ../debian/tmp/usr/bin/apport-cli.py:324 ../bin/apport-cli.py:324
msgid "none"
msgstr "пусто"

#: ../debian/tmp/usr/bin/apport-cli.py:325 ../bin/apport-cli.py:325
#, python-format
msgid "Selected: %s. Multiple choices:"
msgstr "Выбрано: %s. Несколько вариантов:"

#: ../debian/tmp/usr/bin/apport-cli.py:341 ../bin/apport-cli.py:341
msgid "Choices:"
msgstr "Выбор:"

#: ../debian/tmp/usr/bin/apport-cli.py:355 ../bin/apport-cli.py:355
msgid "Path to file (Enter to cancel):"
msgstr "Путь к файлу (Enter — отмена):"

#: ../debian/tmp/usr/bin/apport-cli.py:361 ../bin/apport-cli.py:361
msgid "File does not exist."
msgstr "Файл не существует."

#: ../debian/tmp/usr/bin/apport-cli.py:363 ../bin/apport-cli.py:363
msgid "This is a directory."
msgstr "Это — директория."

#: ../debian/tmp/usr/bin/apport-cli.py:369 ../bin/apport-cli.py:369
msgid "To continue, you must visit the following URL:"
msgstr "Чтобы продолжить, вы должны пройти по следующему адресу:"

#: ../debian/tmp/usr/bin/apport-cli.py:371 ../bin/apport-cli.py:371
msgid ""
"You can launch a browser now, or copy this URL into a browser on another "
"computer."
msgstr ""
"Теперь вы можете открыть браузер или скопировать URL в браузер на другой "
"компьютер."

#: ../debian/tmp/usr/bin/apport-cli.py:373 ../bin/apport-cli.py:373
msgid "Launch a browser now"
msgstr "Запустить браузер"

#: ../debian/tmp/usr/bin/apport-cli.py:388 ../bin/apport-cli.py:388
msgid "No pending crash reports. Try --help for more information."
msgstr "Нет ожидающих сообщений о сбоях. Попробуйте ключ --help."

#: ../kde/apport-kde-mime.desktop.in.h:1 ../kde/apport-kde.desktop.in.h:1
#: ../gtk/apport-gtk.desktop.in.h:1
msgid "Report a problem..."
msgstr "Сообщить о неполадке..."

#: ../kde/apport-kde-mime.desktop.in.h:2 ../kde/apport-kde.desktop.in.h:2
#: ../gtk/apport-gtk.desktop.in.h:2
msgid "Report a malfunction to the developers"
msgstr "Сообщить о недоработке разработчикам"

#: ../data/kernel_oops.py:29 ../debian/tmp/usr/share/apport/kernel_oops.py:29
msgid "Your system might become unstable now and might need to be restarted."
msgstr "Система может стать нестабильной, возможно потребуется перезагрузка."

#: ../apport/com.ubuntu.apport.policy.in.h:1
msgid "Collect system information"
msgstr "Собрать сведения о системе"

#: ../apport/com.ubuntu.apport.policy.in.h:2
msgid ""
"Authentication is required to collect system information for this problem "
"report"
msgstr ""
"Чтобы отправить отчёт о неполадке и собрать сведения о системе, необходимо "
"выполнить аутентификацию"

#: ../apport/com.ubuntu.apport.policy.in.h:3
msgid "System problem reports"
msgstr "Отчёты о системных ошибках"

#: ../apport/com.ubuntu.apport.policy.in.h:4
msgid ""
"Please enter your password to access problem reports of system programs"
msgstr ""
"Введите свой пароль для доступа к отчётам об ошибках в системных программах"

#: ../bin/apport-retrace.py:34 ../debian/tmp/usr/bin/apport-retrace.py:34
msgid "Do not put the new traces into the report, but write them to stdout."
msgstr ""
"Не добавлять новые трассировки в отчет, а посылать на стандартный вывод."

#: ../bin/apport-retrace.py:36 ../debian/tmp/usr/bin/apport-retrace.py:36
msgid ""
"Start an interactive gdb session with the report's core dump (-o ignored; "
"does not rewrite report)"
msgstr ""
"Запустить интерактивный сеанс gdb с дампом ядра из отчёта (-o игнорируется; "
"отчёт не перезаписывается)"

#: ../bin/apport-retrace.py:38 ../debian/tmp/usr/bin/apport-retrace.py:38
msgid ""
"Write modified report to given file instead of changing the original report"
msgstr ""
"Сохранить измененный отчет в файл вместо изменения оригинального отчета"

#: ../bin/apport-retrace.py:41 ../debian/tmp/usr/bin/apport-retrace.py:41
msgid "Remove the core dump from the report after stack trace regeneration"
msgstr "Удалить дамп ядра из отчёта после восстановления трассировки стека"

#: ../bin/apport-retrace.py:43 ../debian/tmp/usr/bin/apport-retrace.py:43
msgid "Override report's CoreFile"
msgstr "Заменить CoreFile в отчёте"

#: ../bin/apport-retrace.py:45 ../debian/tmp/usr/bin/apport-retrace.py:45
msgid "Override report's ExecutablePath"
msgstr "Заменить ExecutablePath в отчёте"

#: ../bin/apport-retrace.py:47 ../debian/tmp/usr/bin/apport-retrace.py:47
msgid "Override report's ProcMaps"
msgstr "Заменить ProcMaps в отчёте"

#: ../bin/apport-retrace.py:49 ../debian/tmp/usr/bin/apport-retrace.py:49
msgid "Rebuild report's Package information"
msgstr "Заново построить информацию о пакетах в отчёте"

#: ../bin/apport-retrace.py:51 ../debian/tmp/usr/bin/apport-retrace.py:51
msgid ""
"Build a temporary sandbox and download/install the necessary packages and "
"debug symbols in there; without this option it assumes that the necessary "
"packages and debug symbols are already installed in the system. The argument "
"points to the packaging system configuration base directory; if you specify "
"\"system\", it will use the system configuration files, but will then only "
"be able to retrace crashes that happened on the currently running release."
msgstr ""
"Создать временную среду, затем загрузить/установить в неё необходимые пакеты "
"и отладочные символы; без этого параметра предполагается, что необходимые "
"пакеты и отладочные символы в системе уже установлены. Аргумент указывает на "
"базовую папку конфигурации системы пакетов; если вы указали \"system\", "
"будут использоваться системные файлы конфигурации, но только в случае "
"обнаружения аварийных ситуаций, произошедших в выпуске системы, работающем в "
"данный момент."

#: ../bin/apport-retrace.py:53 ../debian/tmp/usr/bin/apport-retrace.py:53
msgid ""
"Build another temporary sandbox for installing gdb and its dependencies "
"using the same release as the report rather than whatever version of gdb you "
"have installed."
msgstr ""
"Создать ещё одну временную изолированную среду для установки gdb и его "
"зависимостей, используя вместо установленной у вас версии gdb выпуск, "
"совпадающий с отчётом."

#: ../bin/apport-retrace.py:55 ../debian/tmp/usr/bin/apport-retrace.py:55
msgid ""
"Report download/install progress when installing packages into sandbox"
msgstr ""
"Сообщать о ходе выполнения загрузки/установки пакетов во временную среду"

#: ../bin/apport-retrace.py:57 ../debian/tmp/usr/bin/apport-retrace.py:57
msgid "Prepend timestamps to log messages, for batch operation"
msgstr ""
"Добавлять временные отметки до сообщений в журнале, для групповых операций"

#: ../bin/apport-retrace.py:59 ../debian/tmp/usr/bin/apport-retrace.py:59
msgid ""
"Create and use third-party repositories from origins specified in reports"
msgstr ""
"Создавать и использовать сторонние репозитории из источников, указанных в "
"отчётах"

#: ../bin/apport-retrace.py:61 ../debian/tmp/usr/bin/apport-retrace.py:61
msgid "Cache directory for packages downloaded in the sandbox"
msgstr "Папка для сохранения пакетов, загружаемых во временную среду"

#: ../bin/apport-retrace.py:63 ../debian/tmp/usr/bin/apport-retrace.py:63
msgid ""
"Directory for unpacked packages. Future runs will assume that any already "
"downloaded package is also extracted to this sandbox."
msgstr ""
"Директория для распаковки пакетов. При последующих запусках все уже "
"загруженные пакеты будут распаковываться в это изолированное окружение."

#: ../bin/apport-retrace.py:67 ../debian/tmp/usr/bin/apport-retrace.py:67
msgid ""
"Path to a file with the crash database authentication information. This is "
"used when specifying a crash ID to upload the retraced stack traces (only if "
"neither -g, -o, nor -s are specified)"
msgstr ""
"Путь к файлу с информацией о проверке подлинности базы сбоев. Используется "
"при указании ID сбоя для отправки трассировок стека (только когда -g, -o или "
"-s не указаны)"

#: ../bin/apport-retrace.py:69 ../debian/tmp/usr/bin/apport-retrace.py:69
msgid ""
"Display retraced stack traces and ask for confirmation before sending them "
"to the crash database."
msgstr ""
"Отобразить трассировки и запросить подтверждение перед их отправкой в базу "
"данных сбоев."

#: ../bin/apport-retrace.py:71 ../debian/tmp/usr/bin/apport-retrace.py:71
msgid ""
"Path to the duplicate sqlite database (default: no duplicate checking)"
msgstr ""
"Путь к дублирующей базе данных sqlite (по умолчанию: без проверки дубликатов)"

#: ../bin/apport-retrace.py:73 ../debian/tmp/usr/bin/apport-retrace.py:73
msgid "Do not add StacktraceSource to the report."
msgstr "Не прилагать StacktraceSource к отчёту."

#: ../bin/apport-retrace.py:82 ../debian/tmp/usr/bin/apport-retrace.py:82
msgid "You cannot use -C without -S. Stopping."
msgstr "Нельзя использовать -C без -S. Остановка."

#. translators: don't translate y/n, apport currently only checks for "y"
#: ../bin/apport-retrace.py:115 ../debian/tmp/usr/bin/apport-retrace.py:115
msgid "OK to send these as attachments? [y/n]"
msgstr "Отправить эти приложения? [y/n]"

#: ../debian/tmp/usr/share/apport/apportcheckresume.py:67
#: ../data/apportcheckresume.py:67
msgid ""
"This occurred during a previous suspend, and prevented the system from "
"resuming properly."
msgstr ""
"Это произошло во время предыдущего ждущего режима, что не даёт системе "
"правильно выйти из него."

#: ../debian/tmp/usr/share/apport/apportcheckresume.py:69
#: ../data/apportcheckresume.py:69
msgid ""
"This occurred during a previous hibernation, and prevented the system from "
"resuming properly."
msgstr ""
"Это произошло во время предыдущего спящего режима, что не даёт системе "
"правильно выйти из него."

#: ../debian/tmp/usr/share/apport/apportcheckresume.py:74
#: ../data/apportcheckresume.py:74
msgid ""
"The resume processing hung very near the end and will have appeared to have "
"completed normally."
msgstr ""
"Процесс создания отчёта завис очень близко к завершению; для нормального "
"завершения он должен был появиться."

#: ../kde/apport-kde-mimelnk.desktop.in.h:1
msgid "Apport crash file"
msgstr "Файл отчета Apport"

#: ../debian/tmp/usr/share/apport/apport-gtk.py:161 ../gtk/apport-gtk.py:161
#, python-format
msgid "Sorry, the application %s has stopped unexpectedly."
msgstr "Извините, приложение %s внезапно завершилось."

#: ../debian/tmp/usr/share/apport/apport-gtk.py:164 ../gtk/apport-gtk.py:164
#, python-format
msgid "Sorry, %s has closed unexpectedly."
msgstr "Извините, %s было непредвиденно закрыто."

#: ../debian/tmp/usr/share/apport/apport-gtk.py:239 ../gtk/apport-gtk.py:239
#, python-format
msgid "The application %s has stopped responding."
msgstr "Приложение «%s» перестало отвечать."

#: ../debian/tmp/usr/share/apport/apport-gtk.py:243 ../gtk/apport-gtk.py:243
#, python-format
msgid "The program \"%s\" has stopped responding."
msgstr "Программа «%s» перестала отвечать."

#: ../debian/tmp/usr/share/apport/general-hooks/ubuntu.py:195
#: ../data/general-hooks/ubuntu.py:195
msgid ""
"An Ubuntu package has a file conflict with a package that is not a genuine "
"Ubuntu package."
msgstr ""
"Пакет Ubuntu конфликтует с пакетом, который не является подлинным пакетом "
"Ubuntu."

#: ../debian/tmp/usr/share/apport/general-hooks/ubuntu.py:203
#: ../data/general-hooks/ubuntu.py:203
msgid "You have already encountered this package installation failure."
msgstr "Ошибка с установкой этого пакета уже происходила."

#: ../debian/tmp/usr/share/apport/general-hooks/ubuntu.py:219
#: ../data/general-hooks/ubuntu.py:219
msgid ""
"Your system was initially configured with grub version 2, but you have "
"removed it from your system in favor of grub 1 without configuring it.  To "
"ensure your bootloader configuration is updated whenever a new kernel is "
"available, open a terminal and run:\n"
"\n"
"      sudo apt-get install grub-pc\n"
msgstr ""
"Изначально система была настроена на использование загрузчика GRUB версии 2, "
"но он был заменён на GRUB 1 и не настроен.  Чтобы убедиться в "
"работоспособности загрузчика с новыми параметрами, откройте терминал и "
"выполните команду:\n"
"\n"
"      sudo apt-get install grub-pc\n"
