msgid ""
msgstr ""
"Project-Id-Version: ubuntu-translations\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2019-04-11 20:13+0000\n"
"PO-Revision-Date: 2019-08-27 10:53\n"
"Last-Translator: Andriy Poznakhovskyy (Andriy_Crowdin)\n"
"Language-Team: Ukrainian\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Launchpad-Export-Date: 2019-05-11 12:08+0000\n"
"X-Generator: crowdin.com\n"
"Language: uk_UA\n"
"Plural-Forms: nplurals=4; plural=((n%10==1 && n%100!=11) ? 0 : ((n%10 >= 2 && n%10 <=4 && (n%100 < 12 || n%100 > 14)) ? 1 : ((n%10 == 0 || (n%10 >= 5 && n%10 <=9)) || (n%100 >= 11 && n%100 <= 14)) ? 2 : 3));\n"
"X-Crowdin-Project: ubuntu-translations\n"
"X-Crowdin-Language: uk\n"
"X-Crowdin-File: /master/rosetta-eoan/en_GB/LC_MESSAGES/apport.po\n"

#: ../debian/tmp/usr/share/apport/apport-kde.py:186
#: ../debian/tmp/usr/share/apport/apport-gtk.py:181
#: ../debian/tmp/usr/bin/apport-cli.py:194 ../kde/apport-kde.py:186
#: ../bin/apport-cli.py:194 ../gtk/apport-gtk.py:181 ../gtk/apport-gtk.ui.h:6
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:6
msgid "Send problem report to the developers?"
msgstr "Надіслати розробникам звіт про помилку?"

#: ../debian/tmp/usr/share/apport/apport-kde.py:194
#: ../debian/tmp/usr/share/apport/apport-gtk.py:188 ../kde/apport-kde.py:194
#: ../gtk/apport-gtk.py:188 ../gtk/apport-gtk.ui.h:14
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:14
msgid "Send"
msgstr "Надіслати"

#: ../debian/tmp/usr/share/apport/apport-kde.py:200
#: ../debian/tmp/usr/share/apport/apport-kde.py:238
#: ../debian/tmp/usr/share/apport/apport-gtk.py:169 ../kde/apport-kde.py:200
#: ../kde/apport-kde.py:238 ../gtk/apport-gtk.py:169
#, python-format
msgid "Sorry, %s has experienced an internal error."
msgstr "Вибачте, у %s сталася внутрішня помилка."

#: ../debian/tmp/usr/share/apport/apport-kde.py:208
#: ../debian/tmp/usr/share/apport/apport-gtk.py:259 ../kde/apport-kde.py:208
#: ../gtk/apport-gtk.py:259
#, python-format
msgid "Package: %s"
msgstr "Пакунок: %s"

#: ../debian/tmp/usr/share/apport/apport-kde.py:214
#: ../debian/tmp/usr/share/apport/apport-gtk.py:265 ../kde/apport-kde.py:214
#: ../gtk/apport-gtk.py:265
msgid "Sorry, a problem occurred while installing software."
msgstr "Вибачте, під час встановлення сталася помилка."

#: ../debian/tmp/usr/share/apport/apport-kde.py:220
#: ../debian/tmp/usr/share/apport/apport-gtk.py:274
#: ../debian/tmp/usr/share/apport/apport-gtk.py:289 ../kde/apport-kde.py:220
#: ../gtk/apport-gtk.py:274 ../gtk/apport-gtk.py:289
#, python-format
msgid "The application %s has experienced an internal error."
msgstr "У програмі %s сталася внутрішня помилка."

#: ../debian/tmp/usr/share/apport/apport-kde.py:223
#: ../debian/tmp/usr/share/apport/apport-gtk.py:277 ../kde/apport-kde.py:223
#: ../gtk/apport-gtk.py:277
#, python-format
msgid "The application %s has closed unexpectedly."
msgstr "Програма %s несподівано припинила роботу."

#: ../debian/tmp/usr/share/apport/apport-kde.py:231
#: ../debian/tmp/usr/share/apport/apport-kde.py:244
#: ../debian/tmp/usr/share/apport/apport-gtk.py:216 ../kde/apport-kde.py:231
#: ../kde/apport-kde.py:244 ../gtk/apport-gtk.py:216
msgid "Continue"
msgstr "Продовжити"

#: ../debian/tmp/usr/share/apport/apport-kde.py:234 ../kde/apport-kde.py:234
msgid "Leave Closed"
msgstr "Залишити закритим"

#: ../debian/tmp/usr/share/apport/apport-kde.py:235
#: ../debian/tmp/usr/share/apport/apport-kde.py:381 ../kde/apport-kde.py:235
#: ../kde/apport-kde.py:381
msgid "Relaunch"
msgstr "Перезапустити"

#: ../debian/tmp/usr/share/apport/apport-kde.py:241
#: ../debian/tmp/usr/share/apport/apport-gtk.py:297 ../kde/apport-kde.py:241
#: ../gtk/apport-gtk.py:297 ../gtk/apport-gtk.ui.h:7
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:7
msgid "If you notice further problems, try restarting the computer."
msgstr "Якщо проблема з’явиться знову, спробуйте перезавантажити комп’ютер."

#: ../debian/tmp/usr/share/apport/apport-kde.py:245
#: ../debian/tmp/usr/share/apport/apport-gtk.py:299 ../kde/apport-kde.py:245
#: ../gtk/apport-gtk.py:299
msgid "Ignore future problems of this type"
msgstr "Ігнорувати такі проблеми у майбутньому"

#: ../debian/tmp/usr/share/apport/apport-kde.py:289
#: ../debian/tmp/usr/share/apport/apport-gtk.py:579 ../kde/apport-kde.py:289
#: ../gtk/apport-gtk.py:579
msgid "Hide Details"
msgstr "Сховати подробиці"

#: ../debian/tmp/usr/share/apport/apport-kde.py:292
#: ../debian/tmp/usr/share/apport/apport-gtk.py:204
#: ../debian/tmp/usr/share/apport/apport-gtk.py:575 ../kde/apport-kde.py:292
#: ../gtk/apport-gtk.py:204 ../gtk/apport-gtk.py:575 ../gtk/apport-gtk.ui.h:11
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:11
msgid "Show Details"
msgstr "Показати подробиці"

#: ../debian/tmp/usr/share/apport/apport-kde.py:315 ../kde/apport-kde.py:315
msgid "Username:"
msgstr "Ім'я користувача:"

#: ../debian/tmp/usr/share/apport/apport-kde.py:316 ../kde/apport-kde.py:316
msgid "Password:"
msgstr "Пароль:"

#: ../debian/tmp/usr/share/apport/apport-kde.py:363
#: ../debian/tmp/usr/share/apport/apport-gtk.py:146
#: ../debian/tmp/usr/bin/apport-cli.py:166 ../kde/apport-kde.py:363
#: ../bin/apport-cli.py:166 ../gtk/apport-gtk.py:146
msgid "(binary data)"
msgstr "(двійкові дані)"

#: ../debian/tmp/usr/share/apport/apport-kde.py:406 ../kde/apport-kde.py:406
msgid "Collecting Problem Information"
msgstr "Збір інформації про помилку"

#: ../debian/tmp/usr/share/apport/apport-kde.py:407
#: ../debian/tmp/usr/bin/apport-cli.py:254 ../kde/apport-kde.py:407
#: ../bin/apport-cli.py:254
msgid "Collecting problem information"
msgstr "Збір інформації про помилку"

#: ../debian/tmp/usr/share/apport/apport-kde.py:408 ../kde/apport-kde.py:408
msgid "The collected information can be sent to the developers to improve the application. This might take a few minutes."
msgstr "Зібрані дані можна надіслати розробникам з метою покращення програми. Ви можете витратити на це декілька хвилин."

#: ../debian/tmp/usr/share/apport/apport-kde.py:434 ../kde/apport-kde.py:434
msgid "Uploading Problem Information"
msgstr "Вивантаження інформації про помилку"

#: ../debian/tmp/usr/share/apport/apport-kde.py:435
#: ../debian/tmp/usr/bin/apport-cli.py:267 ../kde/apport-kde.py:435
#: ../bin/apport-cli.py:267 ../gtk/apport-gtk.ui.h:17
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:17
msgid "Uploading problem information"
msgstr "Вивантаження даних щодо проблеми"

#: ../debian/tmp/usr/share/apport/apport-kde.py:436 ../kde/apport-kde.py:436
#: ../gtk/apport-gtk.ui.h:19 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:19
msgid "The collected information is being sent to the bug tracking system. This might take a few minutes."
msgstr "Зібрана інформація пересилається до системи обліку помилок. Це може тривати декілька хвилин."

#: ../debian/tmp/usr/share/apport/apport-kde.py:469
#: ../debian/tmp/usr/share/apport/apport-kde.py:504
#: ../debian/tmp/usr/share/apport/apport-kde.py:524 ../kde/apport-kde.py:469
#: ../kde/apport-kde.py:504 ../kde/apport-kde.py:524 ../gtk/apport-gtk.ui.h:1
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:1
msgid "Apport"
msgstr ""

#: ../gtk/apport-gtk.desktop.in.h:1 ../kde/apport-kde.desktop.in.h:1
#: ../kde/apport-kde-mime.desktop.in.h:1
msgid "Report a problem..."
msgstr "Повідомити про помилку..."

#: ../gtk/apport-gtk.desktop.in.h:2 ../kde/apport-kde.desktop.in.h:2
#: ../kde/apport-kde-mime.desktop.in.h:2
msgid "Report a malfunction to the developers"
msgstr "Звітувати про збій розробникам"

#: ../apport/com.ubuntu.apport.policy.in.h:1
msgid "Collect system information"
msgstr "Зібрати системну інформацію"

#: ../apport/com.ubuntu.apport.policy.in.h:2
msgid "Authentication is required to collect system information for this problem report"
msgstr "Потрібно надати права, щоб зібрати потрібні дані для звітування цієї проблеми"

#: ../apport/com.ubuntu.apport.policy.in.h:3
msgid "System problem reports"
msgstr "Звіти про системні помилки"

#: ../apport/com.ubuntu.apport.policy.in.h:4
msgid "Please enter your password to access problem reports of system programs"
msgstr "Уведіть свій пароль для доступу до звітів про помилки у системних програмах"

#: ../data/general-hooks/ubuntu.py:184
#: ../debian/tmp/usr/share/apport/general-hooks/ubuntu.py:184
msgid "An Ubuntu package has a file conflict with a package that is not a genuine Ubuntu package."
msgstr "Пакунок Ubuntu містить файл, який є конфліктним із файлом з пакунка, який не є офіційним пакунком Ubuntu."

#: ../data/general-hooks/ubuntu.py:192
#: ../debian/tmp/usr/share/apport/general-hooks/ubuntu.py:192
msgid "You have already encountered this package installation failure."
msgstr "Помилка з встановленням цього пакунку вже траплялася."

#: ../data/general-hooks/ubuntu.py:208
#: ../debian/tmp/usr/share/apport/general-hooks/ubuntu.py:208
msgid "Your system was initially configured with grub version 2, but you have removed it from your system in favor of grub 1 without configuring it.  To ensure your bootloader configuration is updated whenever a new kernel is available, open a terminal and run:\n\n"
"      sudo apt-get install grub-pc\n"
msgstr "Початково систему було налаштовано на використання завантажувача GRUB версії 2, але його було замінено на GRUB 1 й не налаштовано. Щоб переконатися у працездатності завантажувача з новими параметрами, відкрийте термінал та виконайте команду:\n\n"
"      sudo apt-get install grub-pc\n"

#: ../kde/apport-kde-mimelnk.desktop.in.h:1
msgid "Apport crash file"
msgstr "Файл аварії Apport"

#: ../debian/tmp/usr/share/apport/kernel_oops.py:29 ../data/kernel_oops.py:29
msgid "Your system might become unstable now and might need to be restarted."
msgstr "Система може стати нестабільною, можливо буде потрібне перезавантаження."

#: ../debian/tmp/usr/bin/apport-retrace.py:34 ../bin/apport-retrace.py:34
msgid "Do not put the new traces into the report, but write them to stdout."
msgstr "Не вкладайте нові записи у звіт, а долучайте їх до stdout."

#: ../debian/tmp/usr/bin/apport-retrace.py:36 ../bin/apport-retrace.py:36
msgid "Start an interactive gdb session with the report's core dump (-o ignored; does not rewrite report)"
msgstr "Початок інтерактивного GDB-сеансу з  дампом у звіті (-o ігнорувати, не записувати у звіт)"

#: ../debian/tmp/usr/bin/apport-retrace.py:38 ../bin/apport-retrace.py:38
msgid "Write modified report to given file instead of changing the original report"
msgstr "Записати змінений звіт до вказаного файлу замість заміни оригінального звіту"

#: ../debian/tmp/usr/bin/apport-retrace.py:41 ../bin/apport-retrace.py:41
msgid "Remove the core dump from the report after stack trace regeneration"
msgstr "Зняти дамп зі звіту після трасування стеку регенерації"

#: ../debian/tmp/usr/bin/apport-retrace.py:43 ../bin/apport-retrace.py:43
msgid "Override report's CoreFile"
msgstr "Перекрити звіти CoreFile"

#: ../debian/tmp/usr/bin/apport-retrace.py:45 ../bin/apport-retrace.py:45
msgid "Override report's ExecutablePath"
msgstr "Перекрити звіти ExecutablePath"

#: ../debian/tmp/usr/bin/apport-retrace.py:47 ../bin/apport-retrace.py:47
msgid "Override report's ProcMaps"
msgstr "Перекрити звіти ProcMaps"

#: ../debian/tmp/usr/bin/apport-retrace.py:49 ../bin/apport-retrace.py:49
msgid "Rebuild report's Package information"
msgstr "Перебудувати звітовий пакунок інформації"

#: ../debian/tmp/usr/bin/apport-retrace.py:51 ../bin/apport-retrace.py:51
msgid "Build a temporary sandbox and download/install the necessary packages and debug symbols in there; without this option it assumes that the necessary packages and debug symbols are already installed in the system. The argument points to the packaging system configuration base directory; if you specify \"system\", it will use the system configuration files, but will then only be able to retrace crashes that happened on the currently running release."
msgstr "Створити тимчасове середовище, далі - завантажити/встановити у ньому необхідні пакунки й налагоджувальні символи; без цього параметру очікується, що необхідні пакунки та налагоджувальні символи у системі вже встановлено. Аргумент вказує на базову теку конфігурації системи пакунків; якщо Ви вказали \"system\", буде використано системні файли конфігурації, але лише у разі виявлення аварійних ситуацій, що виникли у випуску системи, яка працює на дану мить."

#: ../debian/tmp/usr/bin/apport-retrace.py:53 ../bin/apport-retrace.py:53
msgid "Build another temporary sandbox for installing gdb and its dependencies using the same release as the report rather than whatever version of gdb you have installed."
msgstr "Створіть іншу тимчасову пісочницю для встановлення gdb та її залежностей, використовуючи той же випуск, що і звіт, а не іншу версію gdb, яку ви встановили."

#: ../debian/tmp/usr/bin/apport-retrace.py:55 ../bin/apport-retrace.py:55
msgid "Report download/install progress when installing packages into sandbox"
msgstr "Сповіщати про хід виконання завантаження/встановлення пакунків у тимчасовому середовищі"

#: ../debian/tmp/usr/bin/apport-retrace.py:57 ../bin/apport-retrace.py:57
msgid "Prepend timestamps to log messages, for batch operation"
msgstr "Додавати тимчасові мітки до повідомлень у журналі, для групових операцій"

#: ../debian/tmp/usr/bin/apport-retrace.py:59 ../bin/apport-retrace.py:59
msgid "Create and use third-party repositories from origins specified in reports"
msgstr "Створення і використання сторонніх сховищ на основі початкових, вказаних у звітах"

#: ../debian/tmp/usr/bin/apport-retrace.py:61 ../bin/apport-retrace.py:61
msgid "Cache directory for packages downloaded in the sandbox"
msgstr "Тека для збереження пакунків, що заванатажуються у тимчасове середовище"

#: ../debian/tmp/usr/bin/apport-retrace.py:63 ../bin/apport-retrace.py:63
msgid "Directory for unpacked packages. Future runs will assume that any already downloaded package is also extracted to this sandbox."
msgstr "Каталог для розпакування пакунків. При наступних запусках усі вже завантажені пакунки будуть розпаковуватися у це ізольоване оточення."

#: ../debian/tmp/usr/bin/apport-retrace.py:65 ../bin/apport-valgrind.py:66
#: ../bin/apport-retrace.py:65 ../debian/tmp/usr/bin/apport-valgrind.py:66
msgid "Install an extra package into the sandbox (can be specified multiple times)"
msgstr "Встановити у тимчасове середовище додатковий пакунок (може встановлюватися декілька разів)"

#: ../debian/tmp/usr/bin/apport-retrace.py:67 ../bin/apport-retrace.py:67
msgid "Path to a file with the crash database authentication information. This is used when specifying a crash ID to upload the retraced stack traces (only if neither -g, -o, nor -s are specified)"
msgstr "Шлях до файлу з інформацією про автентифікацію бази даних про аварії. Використовується лише якщо вказано ID аварії для відсилання трасувань стеку (за умови, що ні -g, -o , ані -s не вказано)"

#: ../debian/tmp/usr/bin/apport-retrace.py:69 ../bin/apport-retrace.py:69
msgid "Display retraced stack traces and ask for confirmation before sending them to the crash database."
msgstr "Показати перетрасований стек та запитати підтвердження перед відправленням його у базу аварій."

#: ../debian/tmp/usr/bin/apport-retrace.py:71 ../bin/apport-retrace.py:71
msgid "Path to the duplicate sqlite database (default: no duplicate checking)"
msgstr "Шлях до дублікату бази даних sqlite (типово: немає дублікату для перевірки)"

#: ../debian/tmp/usr/bin/apport-retrace.py:73 ../bin/apport-retrace.py:73
msgid "Do not add StacktraceSource to the report."
msgstr "Не додавати StacktraceSource до звіту."

#: ../debian/tmp/usr/bin/apport-retrace.py:82 ../bin/apport-retrace.py:82
msgid "You cannot use -C without -S. Stopping."
msgstr "Неможна використовувати -C без -S. Зупинка."

#. translators: don't translate y/n, apport currently only checks for "y"
#: ../debian/tmp/usr/bin/apport-retrace.py:115 ../bin/apport-retrace.py:115
msgid "OK to send these as attachments? [y/n]"
msgstr "Відіслати їх як вкладення? [так/ні]"

#: ../debian/tmp/usr/bin/apport-cli.py:80 ../bin/apport-cli.py:80
msgid "Press any key to continue..."
msgstr "Натисніть будь-яку клавішу для продовження..."

#: ../debian/tmp/usr/bin/apport-cli.py:87 ../bin/apport-cli.py:87
msgid "What would you like to do? Your options are:"
msgstr "Що ви бажаєте зробити? Варіанти вибору:"

#: ../debian/tmp/usr/bin/apport-cli.py:100 ../bin/apport-cli.py:100
#, python-format
msgid "Please choose (%s):"
msgstr "Будь ласка, виберіть (%s):"

#: ../debian/tmp/usr/bin/apport-cli.py:164 ../bin/apport-cli.py:164
#, python-format
msgid "(%i bytes)"
msgstr "(%i байт)"

#: ../debian/tmp/usr/bin/apport-cli.py:195 ../bin/apport-cli.py:195
msgid "After the problem report has been sent, please fill out the form in the\n"
"automatically opened web browser."
msgstr "Після того, як звіт буде відправлено, заповніть форму\n"
"у вікні браузера, яке автоматично відкрилося."

#: ../debian/tmp/usr/bin/apport-cli.py:198 ../bin/apport-cli.py:198
#, python-format
msgid "&Send report (%s)"
msgstr "&Надіслати звіт (%s)"

#: ../debian/tmp/usr/bin/apport-cli.py:202 ../bin/apport-cli.py:202
msgid "&Examine locally"
msgstr "&Локальна перевірка"

#: ../debian/tmp/usr/bin/apport-cli.py:206 ../bin/apport-cli.py:206
msgid "&View report"
msgstr "&Переглянути звіт"

#: ../debian/tmp/usr/bin/apport-cli.py:207 ../bin/apport-cli.py:207
msgid "&Keep report file for sending later or copying to somewhere else"
msgstr "&Зберегти файл звіту для подальшого відправлення або копіювання будь-куди"

#: ../debian/tmp/usr/bin/apport-cli.py:208 ../bin/apport-cli.py:208
msgid "Cancel and &ignore future crashes of this program version"
msgstr "Скасувати та &ігнорувати майбутні аварії у цій версії програми"

#: ../debian/tmp/usr/bin/apport-cli.py:210
#: ../debian/tmp/usr/bin/apport-cli.py:287
#: ../debian/tmp/usr/bin/apport-cli.py:319
#: ../debian/tmp/usr/bin/apport-cli.py:340 ../bin/apport-cli.py:210
#: ../bin/apport-cli.py:287 ../bin/apport-cli.py:319 ../bin/apport-cli.py:340
msgid "&Cancel"
msgstr "&Скасувати"

#: ../debian/tmp/usr/bin/apport-cli.py:238 ../bin/apport-cli.py:238
msgid "Problem report file:"
msgstr "Файл звіту про помилку:"

#: ../debian/tmp/usr/bin/apport-cli.py:244
#: ../debian/tmp/usr/bin/apport-cli.py:249 ../bin/apport-cli.py:244
#: ../bin/apport-cli.py:249
msgid "&Confirm"
msgstr "&Підтвердити"

#: ../debian/tmp/usr/bin/apport-cli.py:248 ../bin/apport-cli.py:248
#, python-format
msgid "Error: %s"
msgstr "Помилка: %s"

#: ../debian/tmp/usr/bin/apport-cli.py:255 ../bin/apport-cli.py:255
msgid "The collected information can be sent to the developers to improve the\n"
"application. This might take a few minutes."
msgstr "Зібрану інформацію може бути направлено розробникам\n"
"для покращення програми. Це може зайняти декілька хвилин."

#: ../debian/tmp/usr/bin/apport-cli.py:268 ../bin/apport-cli.py:268
msgid "The collected information is being sent to the bug tracking system.\n"
"This might take a few minutes."
msgstr "Зібрана інформація надсилається до системи відстежування помилок.\n"
"Це може зайняти декілька хвилин."

#: ../debian/tmp/usr/bin/apport-cli.py:318 ../bin/apport-cli.py:318
msgid "&Done"
msgstr "&Завершено"

#: ../debian/tmp/usr/bin/apport-cli.py:324 ../bin/apport-cli.py:324
msgid "none"
msgstr "немає"

#: ../debian/tmp/usr/bin/apport-cli.py:325 ../bin/apport-cli.py:325
#, python-format
msgid "Selected: %s. Multiple choices:"
msgstr "Вибрано: %s. Декілька варіянтів:"

#: ../debian/tmp/usr/bin/apport-cli.py:341 ../bin/apport-cli.py:341
msgid "Choices:"
msgstr "Вибір:"

#: ../debian/tmp/usr/bin/apport-cli.py:355 ../bin/apport-cli.py:355
msgid "Path to file (Enter to cancel):"
msgstr "Шлях до файлу (Enter для скасування):"

#: ../debian/tmp/usr/bin/apport-cli.py:361 ../bin/apport-cli.py:361
msgid "File does not exist."
msgstr "Файлу не існує"

#: ../debian/tmp/usr/bin/apport-cli.py:363 ../bin/apport-cli.py:363
msgid "This is a directory."
msgstr "Це каталог."

#: ../debian/tmp/usr/bin/apport-cli.py:369 ../bin/apport-cli.py:369
msgid "To continue, you must visit the following URL:"
msgstr "Щоб продовжити, ви повинні пройти за адресою:"

#: ../debian/tmp/usr/bin/apport-cli.py:371 ../bin/apport-cli.py:371
msgid "You can launch a browser now, or copy this URL into a browser on another computer."
msgstr "Ви можете запустити браузер зараз або скопіювати цю адресу у браузер на іншому комп'ютері."

#: ../debian/tmp/usr/bin/apport-cli.py:373 ../bin/apport-cli.py:373
msgid "Launch a browser now"
msgstr "Запустити браузер"

#: ../debian/tmp/usr/bin/apport-cli.py:388 ../bin/apport-cli.py:388
msgid "No pending crash reports. Try --help for more information."
msgstr "Немає звітів про аварії у очікуванні. Спробуйте --help для детальної інформації."

#: ../bin/apport-valgrind.py:37 ../debian/tmp/usr/bin/apport-valgrind.py:37
msgid "See man page for details."
msgstr "Дивіться подробиці у man-сторінці."

#: ../bin/apport-valgrind.py:43 ../debian/tmp/usr/bin/apport-valgrind.py:43
msgid "specify the log file name produced by valgrind"
msgstr "вкажіть ім’я log-файлу для valgrind"

#: ../bin/apport-valgrind.py:46 ../debian/tmp/usr/bin/apport-valgrind.py:46
msgid "reuse a previously created sandbox dir (SDIR) or, if it does not exist, create it"
msgstr "використовувати раніше створений каталог пісочниці (SDIR) або створити, якщо його не існує"

#: ../bin/apport-valgrind.py:50 ../debian/tmp/usr/bin/apport-valgrind.py:50
msgid "do  not  create  or reuse a sandbox directory for additional debug symbols but rely only on installed debug symbols."
msgstr "не створювати та не використовувати каталог пісочниці для додаткових символів налагодження, а покладатися лише на встановлені символи налагодження."

#: ../bin/apport-valgrind.py:54 ../debian/tmp/usr/bin/apport-valgrind.py:54
msgid "reuse a previously created cache dir (CDIR) or, if it does not exist, create it"
msgstr "використовувати раніше створений каталог кешу (CDIR) або створити, якщо його не існує"

#: ../bin/apport-valgrind.py:58 ../debian/tmp/usr/bin/apport-valgrind.py:58
msgid "report download/install progress when installing packages into sandbox"
msgstr "показувати поступ завантаження/встановлення під час встановлення пакунків у пісочницю"

#: ../bin/apport-valgrind.py:62 ../debian/tmp/usr/bin/apport-valgrind.py:62
msgid "the executable that is run under valgrind's memcheck tool  for memory leak detection"
msgstr "виконуваний файл, який запускається під контролем valgrind memcheck для визначення витоків пам’яті"

#: ../bin/apport-valgrind.py:97 ../debian/tmp/usr/bin/apport-valgrind.py:97
#, python-format
msgid "Error: %s is not an executable. Stopping."
msgstr "Помилка: %s — невиконуваний файл. Зупинка."

#: ../gtk/apport-gtk.ui.h:2 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:2
msgid "Cancel"
msgstr "Скасувати"

#: ../gtk/apport-gtk.ui.h:3 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:3
msgid "OK"
msgstr "Гаразд"

#: ../gtk/apport-gtk.ui.h:4 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:4
msgid "Crash report"
msgstr "Звіт про аварію"

#: ../gtk/apport-gtk.ui.h:5 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:5
msgid "<big><b>Sorry, an internal error happened.</b></big>"
msgstr "<big><b>Вибачте, сталася внутрішня помилка.</b></big>"

#: ../gtk/apport-gtk.ui.h:8 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:8
msgid "Remember this in future"
msgstr "Запам'ятати це на майбутнє"

#: ../gtk/apport-gtk.ui.h:9 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:9
msgid "Ignore future problems of this program version"
msgstr "Ігнорувати подальші збої у цій версії програми"

#: ../gtk/apport-gtk.ui.h:10 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:10
msgid "Relaunch this application"
msgstr "Перезапустити цю програму"

#: ../gtk/apport-gtk.ui.h:12 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:12
msgid "_Examine locally"
msgstr "_Локальна перевірка"

#: ../gtk/apport-gtk.ui.h:13 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:13
msgid "Don't send"
msgstr "Не надсилати"

#: ../gtk/apport-gtk.ui.h:15 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:15
msgid "<big><b>Collecting problem information</b></big>"
msgstr "<big><b>Збір інформації про помилку</b></big>"

#: ../gtk/apport-gtk.ui.h:16 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:16
msgid "Information is being collected that may help the developers fix the problem you report."
msgstr "Проводиться збір інформації, яка може допомогти розробникам виправити цю помилку."

#: ../gtk/apport-gtk.ui.h:18 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:18
msgid "<big><b>Uploading problem information</b></big>"
msgstr "<big><b>Передача інформації про помилку</b></big>"

#: ../bin/apport-unpack.py:22 ../debian/tmp/usr/bin/apport-unpack.py:22
#, python-format
msgid "Usage: %s <report> <target directory>"
msgstr "Використання: %s <report> <target directory>"

#: ../bin/apport-unpack.py:47 ../debian/tmp/usr/bin/apport-unpack.py:47
msgid "Destination directory exists and is not empty."
msgstr "Каталог адресату існує і не є порожнім."

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:144
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:144
#: ../apport/ui.py:144
msgid "This package does not seem to be installed correctly"
msgstr "Схоже, що цей пакунок встановлено невірно"

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:149
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:149
#: ../apport/ui.py:149
#, python-format
msgid "This is not an official %s package. Please remove any third party package and try again."
msgstr "Даний пакунок %s не є офіційним. Будь ласка, вилучіть усі сторонні пакунки та повторіть знову."

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:166
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:166
#: ../apport/ui.py:166
#, python-format
msgid "You have some obsolete package versions installed. Please upgrade the following packages and check if the problem still occurs:\n\n"
"%s"
msgstr "У системі встановлено застарілі версії деяких пакунків. Оновіть наступні пакунки та перевірте, чи залишилася проблема:\n\n"
"%s"

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:299
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:299
#: ../apport/ui.py:299
msgid "unknown program"
msgstr "невідома програма"

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:300
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:300
#: ../apport/ui.py:300
#, python-format
msgid "Sorry, the program \"%s\" closed unexpectedly"
msgstr "На жаль, програма \"%s\" несподівано закрилася"

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:302
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1402
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:302
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1402
#: ../apport/ui.py:302 ../apport/ui.py:1402
#, python-format
msgid "Problem in %s"
msgstr "Помилка у %s"

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:303
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:303
#: ../apport/ui.py:303
msgid "Your computer does not have enough free memory to automatically analyze the problem and send a report to the developers."
msgstr "На вашому комп'ютері недостатньо вільної пам'яті для автоматичного аналізу проблеми та надсилання розробникам звіту."

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:358
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:366
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:493
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:496
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:696
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1208
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1374
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1378
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:358
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:366
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:493
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:496
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:696
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1208
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1374
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1378
#: ../apport/ui.py:358 ../apport/ui.py:366 ../apport/ui.py:493
#: ../apport/ui.py:496 ../apport/ui.py:696 ../apport/ui.py:1208
#: ../apport/ui.py:1374 ../apport/ui.py:1378
msgid "Invalid problem report"
msgstr "Неправильний звіт про помилку"

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:359
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:359
#: ../apport/ui.py:359
msgid "You are not allowed to access this problem report."
msgstr "Ви не маєте доступу до цього звіту."

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:362
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:362
#: ../apport/ui.py:362
msgid "Error"
msgstr "Помилка"

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:363
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:363
#: ../apport/ui.py:363
msgid "There is not enough disk space available to process this report."
msgstr "Недостатньо місця на диску для обробки цього звіту."

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:474
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:474
#: ../apport/ui.py:474
msgid "Invalid PID"
msgstr "Неправильний PID"

#: ../apport/ui.py:402
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:402
msgid "The specified process ID does not exist."
msgstr ""

#: ../apport/ui.py:405
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:405
msgid "Not your PID"
msgstr ""

#: ../apport/ui.py:406
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:406
msgid "The specified process ID does not belong to you."
msgstr ""

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:447
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:447
#: ../apport/ui.py:447
msgid "No package specified"
msgstr "Не вказано пакунок"

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:448
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:448
#: ../apport/ui.py:448
msgid "You need to specify a package or a PID. See --help for more information."
msgstr "Необхідно вказати пакунок або PID. Наберіть --help для отримання додаткової інформації."

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:471
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:471
#: ../apport/ui.py:471
msgid "Permission denied"
msgstr "У доступі відмовлено"

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:472
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:472
#: ../apport/ui.py:472
msgid "The specified process does not belong to you. Please run this program as the process owner or as root."
msgstr "Зазначений процес Вам не належить. Будь ласка, запустіть програму як власник процесу або як root."

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:475
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:475
#: ../apport/ui.py:475
msgid "The specified process ID does not belong to a program."
msgstr "Зазначений процес ID не належить до програми."

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:494
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:494
#: ../apport/ui.py:494
#, python-format
msgid "Symptom script %s did not determine an affected package"
msgstr "Симптоматичний скрипт %s не може визначити постраждалих пакунків"

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:497
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:497
#: ../apport/ui.py:497
#, python-format
msgid "Package %s does not exist"
msgstr "Пакунку %s не існує"

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:521
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:708
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:713
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:521
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:708
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:713
#: ../apport/ui.py:521 ../apport/ui.py:708 ../apport/ui.py:713
msgid "Cannot create report"
msgstr "Неможливо створити звіт"

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:536
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:582
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:598
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:536
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:582
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:598
#: ../apport/ui.py:536 ../apport/ui.py:582 ../apport/ui.py:598
msgid "Updating problem report"
msgstr "Оновлення звіту про проблеми"

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:537
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:537
#: ../apport/ui.py:537
msgid "You are not the reporter or subscriber of this problem report, or the report is a duplicate or already closed.\n\n"
"Please create a new report using \"apport-bug\"."
msgstr "Ви не є відправником чи отримувачем звіту про дану проблему, можливо звіт вже існує або вже був закритий.\n\n"
"Будь-ласка, створіть новий звіт за допомогою \"apport-bug\"."

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:546
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:546
#: ../apport/ui.py:546
msgid "You are not the reporter of this problem report. It is much easier to mark a bug as a duplicate of another than to move your comments and attachments to a new bug.\n\n"
"Subsequently, we recommend that you file a new bug report using \"apport-bug\" and make a comment in this bug about the one you file.\n\n"
"Do you really want to proceed?"
msgstr "Ви не створювали даний звіт. Набагато легше маркувати помилку як ту що вже існує, ніж створювати свої коментарі та відправляти нову помилку.\n\n"
"Надалі, ми рекомендуємо Вам подати нове повідомлення про помилку з використанням \"apport-bug\", та коментувати помилку у тому ж файлі.\n\n"
"Ви справді бажаєте продовжити?"

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:583
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:599
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:583
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:599
#: ../apport/ui.py:583 ../apport/ui.py:599
msgid "No additional information collected."
msgstr "Не зібрано додаткової інформації."

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:650
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:650
#: ../apport/ui.py:650
msgid "What kind of problem do you want to report?"
msgstr "Про яку проблему ви бажаєте повідомити?"

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:667
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:667
#: ../apport/ui.py:667
msgid "Unknown symptom"
msgstr "Невідомий симптом"

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:668
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:668
#: ../apport/ui.py:668
#, python-format
msgid "The symptom \"%s\" is not known."
msgstr "Симптом «%s» не відомий"

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:699
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:699
#: ../apport/ui.py:699
msgid "After closing this message please click on an application window to report a problem about it."
msgstr "Після того, як сховаєте дане повідомлення, будь-ласка, клацніть на вікно програми для того, щоб відіслати звіт про помилку."

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:709
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:714
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:709
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:714
#: ../apport/ui.py:709 ../apport/ui.py:714
msgid "xprop failed to determine process ID of the window"
msgstr "Помилка xprop: не вдалося визначити ID процесу вікна"

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:728
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:728
#: ../apport/ui.py:728
msgid "%prog <report number>"
msgstr "%prog <номер звіту>"

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:730
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:730
#: ../apport/ui.py:730
msgid "Specify package name."
msgstr "Вкажіть назву пакунку."

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:732
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:783
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:732
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:783
#: ../apport/ui.py:732 ../apport/ui.py:783
msgid "Add an extra tag to the report. Can be specified multiple times."
msgstr "Додати додаткову мітку до звіту. Може бути задано декілька разів."

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:762
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:762
#: ../apport/ui.py:762
msgid "%prog [options] [symptom|pid|package|program path|.apport/.crash file]"
msgstr "%prog [параметри] [симптом|pid|пакунок|шлях програми|.apport/.crash file]"

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:765
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:765
#: ../apport/ui.py:765
msgid "Start in bug filing mode. Requires --package and an optional --pid, or just a --pid. If neither is given, display a list of known symptoms. (Implied if a single argument is given.)"
msgstr "Запуск у режимі запису помилки у файл. Вимагає --package і факультативно --pid, або просто --pid. Якщо ні одного не вказано, показати список відомих симптомів. (Мається на увазі якщо задано один аргумент.)"

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:767
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:767
#: ../apport/ui.py:767
msgid "Click a window as a target for filing a problem report."
msgstr "Клацніть на цільове вікно для заповнення звіту про помилку."

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:769
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:769
#: ../apport/ui.py:769
msgid "Start in bug updating mode. Can take an optional --package."
msgstr "Запустити у режимі оновлення помилки. Може виконуватися з ключем --package."

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:771
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:771
#: ../apport/ui.py:771
msgid "File a bug report about a symptom. (Implied if symptom name is given as only argument.)"
msgstr "Відправити звіт про помилку з симптомом. (Мається на увазі, якщо ім'я симптому дано як єдиний аргумент.)"

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:773
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:773
#: ../apport/ui.py:773
msgid "Specify package name in --file-bug mode. This is optional if a --pid is specified. (Implied if package name is given as only argument.)"
msgstr "Вкажіть назву пакунку у режимі --file-bug. Необов’язково якщо вказано --pid. (Припустимо що назва пакунку вказана у якості єдиного аргументу)"

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:775
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:775
#: ../apport/ui.py:775
msgid "Specify a running program in --file-bug mode. If this is specified, the bug report will contain more information.  (Implied if pid is given as only argument.)"
msgstr "Вкажіть програму, що виконується, у режимі --file-bug. У цьому випадку звіт про помилку міститиме більше інформації. (Мається на увазі, що вказано єдиний аргумент- pid.)"

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:777
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:777
#: ../apport/ui.py:777
msgid "The provided pid is a hanging application."
msgstr "Вказаний ідентифікатор належить процесу, який не відповідає."

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:779
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:779
#: ../apport/ui.py:779
#, python-format
msgid "Report the crash from given .apport or .crash file instead of the pending ones in %s. (Implied if file is given as only argument.)"
msgstr "Повідомити про аварію із наданого файлу .apport або .crash замість файлів у черзі в %s. (За умови, що файл надано у якості єдиного параметру.)"

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:781
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:781
#: ../apport/ui.py:781
msgid "In bug filing mode, save the collected information into a file instead of reporting it. This file can then be reported later on from a different machine."
msgstr "У режимі збору помилок замість надсилати зібрану інформацію, збережіть її у файл. Цей файл можна буде відправити пізніше з іншого комп'ютера."

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:785
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:785
#: ../apport/ui.py:785
msgid "Print the Apport version number."
msgstr "Надрукувати номер версії Apport ."

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:936
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:936
#: ../apport/ui.py:936
msgid "This will launch apport-retrace in a terminal window to examine the crash."
msgstr "Буде здійснено запуск «apport-retrace» у вікні терміналу для перевірки аварійного завершення роботи."

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:937
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:937
#: ../apport/ui.py:937
msgid "Run gdb session"
msgstr "Запустити сеанс gdb"

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:938
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:938
#: ../apport/ui.py:938
msgid "Run gdb session without downloading debug symbols"
msgstr "Запустити сеанс gdb, оминувши завантаження символів відлагодження"

#. TRANSLATORS: %s contains the crash report file name
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:940
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:940
#: ../apport/ui.py:940
#, python-format
msgid "Update %s with fully symbolic stack trace"
msgstr "Оновити %s з повним відстеженням символічного стеку"

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:976
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:976
#: ../apport/ui.py:976
msgid "Can't remember send report status settings"
msgstr "Неможливо запам'ятати параметри стану для надсилання звіту"

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:977
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:977
#: ../apport/ui.py:977
msgid "Saving crash reporting state failed. Can't set auto or never reporting mode."
msgstr "Збереження стану звітування про аварію завершилося невдачею. Неможливо встановити режим звітування auto або never."

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1036
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1046
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1036
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1046
#: ../apport/ui.py:1036 ../apport/ui.py:1046
msgid "This problem report applies to a program which is not installed any more."
msgstr "Цей звіт про помилку належить до програми, якої більше немає у системі."

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1061
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1061
#: ../apport/ui.py:1061
#, python-format
msgid "The problem happened with the program %s which changed since the crash occurred."
msgstr "Проблема у програмі %s, до якої були внесені зміни з моменту аварійного завершення її роботи."

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1108
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1165
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1380
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1108
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1165
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1380
#: ../apport/ui.py:1108 ../apport/ui.py:1165 ../apport/ui.py:1380
msgid "This problem report is damaged and cannot be processed."
msgstr "Цей звіт про помилку пошкоджено та не може бути оброблено."

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1116
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1116
#: ../apport/ui.py:1116
#, python-format
msgid "This report is about a snap published by %s. Contact them via %s for help."
msgstr "Це звіт про snap-пакунок, що його опублікував %s. Зверніться до них по допомогу через %s."

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1119
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1119
#: ../apport/ui.py:1119
#, python-format
msgid "This report is about a snap published by %s. No contact address has been provided; visit the forum at https://forum.snapcraft.io/ for help."
msgstr "Це звіт про snap-пакунок, що його опублікував %s. Контактної адреси не зазначено, отримайте допомогу на форумі https://forum.snapcraft.io/."

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1123
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1123
#: ../apport/ui.py:1123
msgid "This report is about a package that is not installed."
msgstr "Цей звіт стосується пакунку, який не встановлено."

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1127
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1127
#: ../apport/ui.py:1127
msgid "An error occurred while attempting to process this problem report:"
msgstr "Сталася помилка при спробі обробки звіту:"

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1134
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1134
#: ../apport/ui.py:1134
#, python-format
msgid "You are about to report a bug against the deb package, but you also a have snap published by %s installed. You can contact them via %s for help. Do you want to continue with the bug report against the deb?"
msgstr "Ви збираєтеся повідомити про помилку в пакунку deb, але у вас також встановлений snap-пакунок, що його опублікував %s. Ви можете звернутися до них по допомогу через %s. Ви хочете продовжити створювати подвідомлення про помилку щодо пакунку deb?"

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1136
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1136
#: ../apport/ui.py:1136
#, python-format
msgid "You are about to report a bug against the deb package, but you also a have snap published by %s installed. For the snap, no contact address has been provided; visit the forum at https://forum.snapcraft.io/ for help. Do you want to continue with the bug report against the deb?"
msgstr "Ви збираєтеся повідомити про помилку в пакунку deb, але у вас також встановлений snap-пакунок, що його опублікував %s. Для snap-пакунку контактну адресу не зазначено, отримайте допомогу на форумі https://forum.snapcraft.io/. Ви хочете продовжити створювати подвідомлення про помилку щодо пакунку deb?"

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1209
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1209
#: ../apport/ui.py:1209
msgid "Could not determine the package or source package name."
msgstr "Не вдалося визначити ім'я пакунку або ім'я пакунку з вихідним кодом."

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1227
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1227
#: ../apport/ui.py:1227
msgid "Unable to start web browser"
msgstr "Неможливо запустити веб-переглядач"

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1228
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1228
#: ../apport/ui.py:1228
#, python-format
msgid "Unable to start web browser to open %s."
msgstr "Не вдається запустити веб-переглядач, щоб відкрити %s."

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1328
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1328
#: ../apport/ui.py:1328
#, python-format
msgid "Please enter your account information for the %s bug tracking system"
msgstr "Будь ласка, уведіть інформацію про обліковий запис для %s системи стеження за помилками"

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1340
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1340
#: ../apport/ui.py:1340
msgid "Network problem"
msgstr "Проблема з мережею"

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1342
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1342
#: ../apport/ui.py:1342
msgid "Cannot connect to crash database, please check your Internet connection."
msgstr "Не вдається під'єднатися до пошкодженої бази даних, будь ласка, перевірте з'єднання з мережею Інтернет."

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1369
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1369
#: ../apport/ui.py:1369
msgid "Memory exhaustion"
msgstr "Пам'ять вичерпано"

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1370
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1370
#: ../apport/ui.py:1370
msgid "Your system does not have enough memory to process this crash report."
msgstr "У системі недостатньо пам'яті для обробки цього звіту про аварію."

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1405
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1405
#: ../apport/ui.py:1405
#, python-format
msgid "The problem cannot be reported:\n\n"
"%s"
msgstr "Не вдається повідомити про помилку:\n\n"
"%s"

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1461
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1468
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1461
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1468
#: ../apport/ui.py:1461 ../apport/ui.py:1468
msgid "Problem already known"
msgstr "Про помилку вже відомо"

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1462
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1462
#: ../apport/ui.py:1462
msgid "This problem was already reported in the bug report displayed in the web browser. Please check if you can add any further information that might be helpful for the developers."
msgstr "Про цю помилку вже відомо. Звіт про неї відкритий у вашому браузері. Будь ласка, перевірте, чи можете ви додати до нього іншу корисну інформацію, яка могла б допомогти розробникам."

#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1469
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1469
#: ../apport/ui.py:1469
msgid "This problem was already reported to developers. Thank you!"
msgstr "Про цю проблему розробникам вже відомо. Дякуємо!"

#: ../data/apportcheckresume.py:67
#: ../debian/tmp/usr/share/apport/apportcheckresume.py:67
msgid "This occurred during a previous suspend, and prevented the system from resuming properly."
msgstr "Це сталося під час попереднього сеансу призупинення роботи і призвело до неможливості належного відновлення роботи системи."

#: ../data/apportcheckresume.py:69
#: ../debian/tmp/usr/share/apport/apportcheckresume.py:69
msgid "This occurred during a previous hibernation, and prevented the system from resuming properly."
msgstr "Це сталося під час попереднього сеансу присипляння і призвело до неможливості належного відновлення роботи системи."

#: ../data/apportcheckresume.py:74
#: ../debian/tmp/usr/share/apport/apportcheckresume.py:74
msgid "The resume processing hung very near the end and will have appeared to have completed normally."
msgstr "Обробка даних звіту зависла дуже близько до кінця і буде, як видається, завершена нормально."

#: ../debian/tmp/usr/share/apport/apport-gtk.py:161 ../gtk/apport-gtk.py:161
#, python-format
msgid "Sorry, the application %s has stopped unexpectedly."
msgstr "Перепрошуємо, програма %s неочікувано зупинилася."

#: ../debian/tmp/usr/share/apport/apport-gtk.py:164 ../gtk/apport-gtk.py:164
#, python-format
msgid "Sorry, %s has closed unexpectedly."
msgstr "Вибачте, %s було несподівано завершено."

#: ../debian/tmp/usr/share/apport/apport-gtk.py:239 ../gtk/apport-gtk.py:239
#, python-format
msgid "The application %s has stopped responding."
msgstr "Програма %s перестала відповідати."

#: ../debian/tmp/usr/share/apport/apport-gtk.py:243 ../gtk/apport-gtk.py:243
#, python-format
msgid "The program \"%s\" has stopped responding."
msgstr "Програма \"%s\" перестала відповідати."

