# Belarusian translation for apport
# Copyright (c) 2007 Rosetta Contributors and Canonical Ltd 2007
# This file is distributed under the same license as the apport package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2007.
#
msgid ""
msgstr ""
"Project-Id-Version: apport\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2020-03-27 07:18+0000\n"
"PO-Revision-Date: 2015-12-23 15:55+0000\n"
"Last-Translator: XiveZ <kyrsant2008@list.ru>\n"
"Language-Team: Belarusian <be@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Launchpad-Export-Date: 2020-05-03 16:37+0000\n"
"X-Generator: Launchpad (build fbdff7602bd10fb883bf7e2ddcc7fd5a16f60398)\n"
"Language: be\n"

#: ../gtk/apport-gtk.py:146 ../bin/apport-cli.py:166
#: ../debian/tmp/usr/share/apport/apport-kde.py:363
#: ../debian/tmp/usr/share/apport/apport-gtk.py:146 ../kde/apport-kde.py:363
#: ../debian/tmp/usr/bin/apport-cli.py:166
msgid "(binary data)"
msgstr "(двайковыя дадзеныя)"

#: ../gtk/apport-gtk.py:161 ../debian/tmp/usr/share/apport/apport-gtk.py:161
#, python-format
msgid "Sorry, the application %s has stopped unexpectedly."
msgstr "Выбачайце, прылада %s нечакана прыпынілася."

#: ../gtk/apport-gtk.py:164 ../debian/tmp/usr/share/apport/apport-gtk.py:164
#, python-format
msgid "Sorry, %s has closed unexpectedly."
msgstr "Выбачайце, %s нечакана зачынілася."

#: ../gtk/apport-gtk.py:169 ../debian/tmp/usr/share/apport/apport-kde.py:200
#: ../debian/tmp/usr/share/apport/apport-kde.py:238
#: ../debian/tmp/usr/share/apport/apport-gtk.py:169 ../kde/apport-kde.py:200
#: ../kde/apport-kde.py:238
#, python-format
msgid "Sorry, %s has experienced an internal error."
msgstr "Прабачце, у %s адбылася ўнутраная памылка."

#: ../gtk/apport-gtk.py:181 ../bin/apport-cli.py:194
#: ../debian/tmp/usr/share/apport/apport-kde.py:186
#: ../debian/tmp/usr/share/apport/apport-gtk.py:181 ../kde/apport-kde.py:186
#: ../debian/tmp/usr/bin/apport-cli.py:194 ../gtk/apport-gtk.ui.h:6
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:6
msgid "Send problem report to the developers?"
msgstr "Даслаць распрацоўшчыкам паведамленне аб праблеме?"

#: ../gtk/apport-gtk.py:188 ../debian/tmp/usr/share/apport/apport-kde.py:194
#: ../debian/tmp/usr/share/apport/apport-gtk.py:188 ../kde/apport-kde.py:194
#: ../gtk/apport-gtk.ui.h:14 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:14
msgid "Send"
msgstr "Даслаць"

#: ../gtk/apport-gtk.py:204 ../gtk/apport-gtk.py:575
#: ../debian/tmp/usr/share/apport/apport-kde.py:292
#: ../debian/tmp/usr/share/apport/apport-gtk.py:204
#: ../debian/tmp/usr/share/apport/apport-gtk.py:575 ../kde/apport-kde.py:292
#: ../gtk/apport-gtk.ui.h:11 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:11
msgid "Show Details"
msgstr "Паказаць падрабязнасці"

#: ../gtk/apport-gtk.py:216 ../debian/tmp/usr/share/apport/apport-kde.py:231
#: ../debian/tmp/usr/share/apport/apport-kde.py:244
#: ../debian/tmp/usr/share/apport/apport-gtk.py:216 ../kde/apport-kde.py:231
#: ../kde/apport-kde.py:244
msgid "Continue"
msgstr "Працягнуць"

#: ../gtk/apport-gtk.py:239 ../debian/tmp/usr/share/apport/apport-gtk.py:239
#, python-format
msgid "The application %s has stopped responding."
msgstr "Дадатак %s перастаў адказваць."

#: ../gtk/apport-gtk.py:243 ../debian/tmp/usr/share/apport/apport-gtk.py:243
#, python-format
msgid "The program \"%s\" has stopped responding."
msgstr "Праграма \"%s\" перастала адказваць."

#: ../gtk/apport-gtk.py:259 ../debian/tmp/usr/share/apport/apport-kde.py:208
#: ../debian/tmp/usr/share/apport/apport-gtk.py:259 ../kde/apport-kde.py:208
#, python-format
msgid "Package: %s"
msgstr "Пакет: %s"

#: ../gtk/apport-gtk.py:265 ../debian/tmp/usr/share/apport/apport-kde.py:214
#: ../debian/tmp/usr/share/apport/apport-gtk.py:265 ../kde/apport-kde.py:214
msgid "Sorry, a problem occurred while installing software."
msgstr "Прабачце, пры ўсталяванні адбылася памылка."

#: ../gtk/apport-gtk.py:274 ../gtk/apport-gtk.py:289
#: ../debian/tmp/usr/share/apport/apport-kde.py:220
#: ../debian/tmp/usr/share/apport/apport-gtk.py:274
#: ../debian/tmp/usr/share/apport/apport-gtk.py:289 ../kde/apport-kde.py:220
#, python-format
msgid "The application %s has experienced an internal error."
msgstr "У дадатку %s адбылася ўнутраная памылка."

#: ../gtk/apport-gtk.py:277 ../debian/tmp/usr/share/apport/apport-kde.py:223
#: ../debian/tmp/usr/share/apport/apport-gtk.py:277 ../kde/apport-kde.py:223
#, python-format
msgid "The application %s has closed unexpectedly."
msgstr "Дастасаванне %s нечакана зачынілася."

#: ../gtk/apport-gtk.py:297 ../debian/tmp/usr/share/apport/apport-kde.py:241
#: ../debian/tmp/usr/share/apport/apport-gtk.py:297 ../kde/apport-kde.py:241
#: ../gtk/apport-gtk.ui.h:7 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:7
msgid "If you notice further problems, try restarting the computer."
msgstr "Калі праблема з'явіцца зноў, паспрабуйце перазагрузіць кампутар."

#: ../gtk/apport-gtk.py:299 ../debian/tmp/usr/share/apport/apport-kde.py:245
#: ../debian/tmp/usr/share/apport/apport-gtk.py:299 ../kde/apport-kde.py:245
msgid "Ignore future problems of this type"
msgstr "Ігнараваць такія праблемы ў будучыні"

#: ../gtk/apport-gtk.py:579 ../debian/tmp/usr/share/apport/apport-kde.py:289
#: ../debian/tmp/usr/share/apport/apport-gtk.py:579 ../kde/apport-kde.py:289
msgid "Hide Details"
msgstr "Схаваць падрабязнасці"

#: ../apport/ui.py:144
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:144
msgid "This package does not seem to be installed correctly"
msgstr "Падобна на тое, што гэты пакет усталяваны неправільна"

#: ../apport/ui.py:149
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:149
#, python-format
msgid ""
"This is not an official %s package. Please remove any third party package "
"and try again."
msgstr ""
"Дадзены пакет %s не з'яўляецца афіцыйным. Калі ласка, выдаліце ўсе староннія "
"пакеты і паўторыце зноў."

#: ../apport/ui.py:166
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:166
#, python-format
msgid ""
"You have some obsolete package versions installed. Please upgrade the "
"following packages and check if the problem still occurs:\n"
"\n"
"%s"
msgstr ""
"У Вашай сістэме ўсталяваныя састарэўшыя версіі некаторых пакетаў. Абнавіце "
"наступныя пакеты і праверце, ці засталася праблема:\n"
"\n"
"%s"

#: ../apport/ui.py:303
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:303
msgid "unknown program"
msgstr "невядомая праграма"

#: ../apport/ui.py:304
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:304
#, python-format
msgid "Sorry, the program \"%s\" closed unexpectedly"
msgstr "Прабачце, праграма «%s» аварыйна завяршыла сваю работу"

#: ../apport/ui.py:306 ../apport/ui.py:1427
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:306
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1427
#, python-format
msgid "Problem in %s"
msgstr "Праблема ў %s"

#: ../apport/ui.py:307
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:307
msgid ""
"Your computer does not have enough free memory to automatically analyze the "
"problem and send a report to the developers."
msgstr ""
"На Вашым кампутары недастаткова вольнай памяці для таго, каб аўтаматычна "
"прааналізаваць няспраўнасць і даслаць справаздачу распрацоўшчыкам."

#: ../apport/ui.py:362 ../apport/ui.py:370 ../apport/ui.py:513
#: ../apport/ui.py:516 ../apport/ui.py:721 ../apport/ui.py:1233
#: ../apport/ui.py:1399 ../apport/ui.py:1403
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:362
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:370
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:513
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:516
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:721
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1233
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1399
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1403
msgid "Invalid problem report"
msgstr "Няправільная справаздача аб памылцы"

#: ../apport/ui.py:363
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:363
msgid "You are not allowed to access this problem report."
msgstr "У Вас не хапае правоў, каб паведамляць аб праблемах."

#: ../apport/ui.py:366
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:366
msgid "Error"
msgstr "Памылка"

#: ../apport/ui.py:367
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:367
msgid "There is not enough disk space available to process this report."
msgstr "Недастаткова месца на дыску для апрацоўкі дадзенай справаздачы."

#: ../apport/ui.py:405 ../apport/ui.py:494
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:405
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:494
msgid "Invalid PID"
msgstr "Памылковы PID"

#: ../apport/ui.py:406
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:406
msgid "The specified process ID does not exist."
msgstr ""

#: ../apport/ui.py:409
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:409
msgid "Not your PID"
msgstr ""

#: ../apport/ui.py:410
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:410
msgid "The specified process ID does not belong to you."
msgstr ""

#: ../apport/ui.py:461
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:461
msgid "No package specified"
msgstr "Не пазначаны пакет"

#: ../apport/ui.py:462
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:462
msgid ""
"You need to specify a package or a PID. See --help for more information."
msgstr ""
"Неабходна пазначыць пакет альбо PID. Запусціце праграму з параметрам --help "
"каб атрымаць дадатковую інфармацыю."

#: ../apport/ui.py:491
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:491
msgid "Permission denied"
msgstr "Доступ забаронены"

#: ../apport/ui.py:492
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:492
msgid ""
"The specified process does not belong to you. Please run this program as the "
"process owner or as root."
msgstr ""
"Пазначаны працэс запушчэны іншым карыстальнікам. Запусціце дадзеную праграму "
"з правамі ўладальніка працэса альбо адміністратара сістэмы."

#: ../apport/ui.py:495
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:495
msgid "The specified process ID does not belong to a program."
msgstr "Пазначаны PID належыць іншаму працэсу."

#: ../apport/ui.py:514
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:514
#, python-format
msgid "Symptom script %s did not determine an affected package"
msgstr "Сімптаматычны скрыпт %s ня можа вызначыць закрануты пакет"

#: ../apport/ui.py:517
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:517
#, python-format
msgid "Package %s does not exist"
msgstr "Пакет %s не існуе"

#: ../apport/ui.py:546 ../apport/ui.py:733 ../apport/ui.py:738
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:546
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:733
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:738
msgid "Cannot create report"
msgstr "Нельга стварыць справаздачу"

#: ../apport/ui.py:561 ../apport/ui.py:607 ../apport/ui.py:623
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:561
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:607
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:623
msgid "Updating problem report"
msgstr "Абнаўленне справаздачы аб праблеме"

#: ../apport/ui.py:562
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:562
msgid ""
"You are not the reporter or subscriber of this problem report, or the report "
"is a duplicate or already closed.\n"
"\n"
"Please create a new report using \"apport-bug\"."
msgstr ""
"Вы не з'яўляецеся аўтарам альбо атрымальнікам гэтай справаздачы аб праблеме, "
"магчыма яна ўжо існуе ці была зачыненая."

#: ../apport/ui.py:571
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:571
msgid ""
"You are not the reporter of this problem report. It is much easier to mark a "
"bug as a duplicate of another than to move your comments and attachments to "
"a new bug.\n"
"\n"
"Subsequently, we recommend that you file a new bug report using \"apport-"
"bug\" and make a comment in this bug about the one you file.\n"
"\n"
"Do you really want to proceed?"
msgstr ""
"Вы не з'яўляецеся стваральнікам дадзенай справаздачы. Нашмат прасцей, "
"адзначыць памылку што яна ўжо існуе, чым ствараць свае каментары і ўкладаць "
"іх у новую памылку\n"
"\n"
"Пасля, мы рэкамендуем Вам падаць новае паведамленне аб памылцы выкарыстання "
"\"памылка apport\", і зрабіць заўвагу аб гэтай памылцы ў тым жа файле.\n"
"\n"
"Вы сапраўды хочаце працягнуць?"

#: ../apport/ui.py:608 ../apport/ui.py:624
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:608
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:624
msgid "No additional information collected."
msgstr "Не сабрана ніякай дадатковай інфармацыі."

#: ../apport/ui.py:675
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:675
msgid "What kind of problem do you want to report?"
msgstr "Пра які тып праблемы Вы хочаце паведаміць?"

#: ../apport/ui.py:692
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:692
msgid "Unknown symptom"
msgstr "Невядомы сімптом"

#: ../apport/ui.py:693
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:693
#, python-format
msgid "The symptom \"%s\" is not known."
msgstr "Сімптом  \"%s\" невядомы."

#: ../apport/ui.py:724
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:724
msgid ""
"After closing this message please click on an application window to report a "
"problem about it."
msgstr ""
"Пасля закрыцця гэтага паведамлення, калі ласка, націсніце на вакно "
"прыкладання, каб паведаміць аб праблеме."

#: ../apport/ui.py:734 ../apport/ui.py:739
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:734
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:739
msgid "xprop failed to determine process ID of the window"
msgstr "xprop не ўдалося вызначыць ID працэсу акна"

#: ../apport/ui.py:753
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:753
msgid "%prog <report number>"
msgstr "%prog <нумар справаздачы>"

#: ../apport/ui.py:755
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:755
msgid "Specify package name."
msgstr "Пазначце імя пакета."

#: ../apport/ui.py:757 ../apport/ui.py:808
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:757
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:808
msgid "Add an extra tag to the report. Can be specified multiple times."
msgstr ""
"Дадаць дадатковы тэг да справаздачы. Можа быць паказаны некалькі разоў."

#: ../apport/ui.py:787
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:787
msgid ""
"%prog [options] [symptom|pid|package|program path|.apport/.crash file]"
msgstr ""
"%prog [параметры] [прыкмета|pid|пакет|шлях да праграмы|.apport/.crash файл]"

#: ../apport/ui.py:790
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:790
msgid ""
"Start in bug filing mode. Requires --package and an optional --pid, or just "
"a --pid. If neither is given, display a list of known symptoms. (Implied if "
"a single argument is given.)"
msgstr ""
"Запуск у рэжыме адпраўкі справаздачы аб памылцы. Патрабуе параметр --package "
"і неабавязковы --pid, або толькі --pid. Калі параметры не перададзеныя, "
"адлюстроўвае спіс вядомых сімптомаў. (Ужываецца, калі перададзены адзіны "
"параметр.)"

#: ../apport/ui.py:792
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:792
msgid "Click a window as a target for filing a problem report."
msgstr "Цокніце па намечаным акне каб запоўніць справаздачу аб праблеме."

#: ../apport/ui.py:794
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:794
msgid "Start in bug updating mode. Can take an optional --package."
msgstr ""
"Запусціць у рэжыме абнаўлення памылкі. Можа прымаць дадатковы ключ - package."

#: ../apport/ui.py:796
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:796
msgid ""
"File a bug report about a symptom. (Implied if symptom name is given as only "
"argument.)"
msgstr ""
"Адправіць справаздачу аб памылцы з сімптомам. (Ужываецца, калі назва "
"сімптома перададзена ў якасці адзінага параметра.)"

#: ../apport/ui.py:798
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:798
msgid ""
"Specify package name in --file-bug mode. This is optional if a --pid is "
"specified. (Implied if package name is given as only argument.)"
msgstr ""
"Пазначыць імя пакета ў рэжыме --file-bug. Неабавязкова, калі пазначаны --"
"pid. (Ужываецца, калі імя пакета перададзена ў якасці адзінага праметра.)"

#: ../apport/ui.py:800
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:800
msgid ""
"Specify a running program in --file-bug mode. If this is specified, the bug "
"report will contain more information.  (Implied if pid is given as only "
"argument.)"
msgstr ""
"Пазначце запушчаную праграму ў рэжыме - file-bug. У гэтым выпадку "
"справаздача аб памылцы будзе ўтрымліваць больш інфармацыі. (Маецца на ўвазе, "
"што пазначаны адзіны аргумент - pid.)"

#: ../apport/ui.py:802
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:802
msgid "The provided pid is a hanging application."
msgstr "Згаданы ідэнтыфікатар належыць працэсу, які не адказвае."

#: ../apport/ui.py:804
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:804
#, python-format
msgid ""
"Report the crash from given .apport or .crash file instead of the pending "
"ones in %s. (Implied if file is given as only argument.)"
msgstr ""
"Адправіць дадзеныя аб збоі з азначанага файла .apport або .crash замест "
"ччакаемых у %s. (Ужываецца, калі файл перададзены ў якасці адзінага "
"параметра.)"

#: ../apport/ui.py:806
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:806
msgid ""
"In bug filing mode, save the collected information into a file instead of "
"reporting it. This file can then be reported later on from a different "
"machine."
msgstr ""
"У рэжыме збору справаздачы аб памылках, сабраная інфармацыя захоўваецца ў "
"файле замест яе адпраўкі. Гэты файл можна будзе адправіць пазней, ці з "
"іншага кампутара."

#: ../apport/ui.py:810
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:810
msgid "Print the Apport version number."
msgstr "Раздрукаваць нумар версіі Apport ."

#: ../apport/ui.py:961
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:961
msgid ""
"This will launch apport-retrace in a terminal window to examine the crash."
msgstr ""
"Будзе ажыццёўлены запуск «apport-retrace» у акне тэрміналу для праверкі "
"аварыйнага завяршэння працы."

#: ../apport/ui.py:962
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:962
msgid "Run gdb session"
msgstr "Запусціць сеанс gdb"

#: ../apport/ui.py:963
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:963
msgid "Run gdb session without downloading debug symbols"
msgstr "Запусціць сеанс gdb, абыходзячы загрузкі адладкавых сімвалаў"

#. TRANSLATORS: %s contains the crash report file name
#: ../apport/ui.py:965
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:965
#, python-format
msgid "Update %s with fully symbolic stack trace"
msgstr "Абнавіць %s з поўным адсочваннем сімвалічнага стэку"

#: ../apport/ui.py:1001
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1001
msgid "Can't remember send report status settings"
msgstr ""

#: ../apport/ui.py:1002
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1002
msgid ""
"Saving crash reporting state failed. Can't set auto or never reporting mode."
msgstr ""

#: ../apport/ui.py:1061 ../apport/ui.py:1071
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1061
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1071
msgid ""
"This problem report applies to a program which is not installed any more."
msgstr "Дадзеная справаздача адносіцца да праграмы, якая не ўсталявана."

#: ../apport/ui.py:1086
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1086
#, python-format
msgid ""
"The problem happened with the program %s which changed since the crash "
"occurred."
msgstr ""
"Праблема ў праграме %s, да якой былі ўнесены змены з моманту аварыйнага "
"завяршэння яе работы."

#: ../apport/ui.py:1133 ../apport/ui.py:1190 ../apport/ui.py:1405
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1133
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1190
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1405
msgid "This problem report is damaged and cannot be processed."
msgstr "Дадзеная справаздача аб непаладцы пашкоджана і не можа апрацоўвацца."

#: ../apport/ui.py:1141
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1141
#, python-format
msgid ""
"This report is about a snap published by %s. Contact them via %s for help."
msgstr ""

#: ../apport/ui.py:1144
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1144
#, python-format
msgid ""
"This report is about a snap published by %s. No contact address has been "
"provided; visit the forum at https://forum.snapcraft.io/ for help."
msgstr ""

#: ../apport/ui.py:1148
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1148
msgid "This report is about a package that is not installed."
msgstr ""

#: ../apport/ui.py:1152
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1152
msgid "An error occurred while attempting to process this problem report:"
msgstr "Адбылася памылка пры спробе апрацоўкі справаздачы:"

#: ../apport/ui.py:1159
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1159
#, python-format
msgid ""
"You are about to report a bug against the deb package, but you also a have "
"snap published by %s installed. You can contact them via %s for help. Do you "
"want to continue with the bug report against the deb?"
msgstr ""

#: ../apport/ui.py:1161
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1161
#, python-format
msgid ""
"You are about to report a bug against the deb package, but you also a have "
"snap published by %s installed. For the snap, no contact address has been "
"provided; visit the forum at https://forum.snapcraft.io/ for help. Do you "
"want to continue with the bug report against the deb?"
msgstr ""

#: ../apport/ui.py:1234
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1234
msgid "Could not determine the package or source package name."
msgstr "Немагчыма вызначыць імя пакету альбо крыніцы."

#: ../apport/ui.py:1252
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1252
msgid "Unable to start web browser"
msgstr "Не атрымалася запусціць вэб-браўзэр"

#: ../apport/ui.py:1253
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1253
#, python-format
msgid "Unable to start web browser to open %s."
msgstr "Немагчыма запусціць вэб-браўзэр, каб адчыніць %s."

#: ../apport/ui.py:1353
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1353
#, python-format
msgid "Please enter your account information for the %s bug tracking system"
msgstr ""
"Калі ласка, увядзіце інфармацыю аб уліковым запісы для %s  сістэмы сачэння "
"за памылкамі"

#: ../apport/ui.py:1365
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1365
msgid "Network problem"
msgstr "Праблема з сеткай"

#: ../apport/ui.py:1367
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1367
msgid ""
"Cannot connect to crash database, please check your Internet connection."
msgstr ""
"Не атрымоўваецца падлучыцца да базы дадзеных па збоях, калі ласка, праверце "
"падлучэнне да Інтэрнэту."

#: ../apport/ui.py:1394
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1394
msgid "Memory exhaustion"
msgstr "Нястача памяці"

#: ../apport/ui.py:1395
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1395
msgid "Your system does not have enough memory to process this crash report."
msgstr ""
"У сістэме недастаткова памяці для апрацоўкі дадзенай справаздачы аб памылцы."

#: ../apport/ui.py:1430
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1430
#, python-format
msgid ""
"The problem cannot be reported:\n"
"\n"
"%s"
msgstr ""
"Немагчыма паведаміць аб праблеме:\n"
"\n"
"%s"

#: ../apport/ui.py:1486 ../apport/ui.py:1493
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1486
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1493
msgid "Problem already known"
msgstr "Праблема ўжо вядомая"

#: ../apport/ui.py:1487
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1487
msgid ""
"This problem was already reported in the bug report displayed in the web "
"browser. Please check if you can add any further information that might be "
"helpful for the developers."
msgstr ""
"Аб дадзенай няспраўнасці ўжо вядома. Існуючая справаздача аб ёй адкрыта ў "
"Вашым браўзэры. Калі ласка, праверце, ці можаце Вы дадаць да яе карысную "
"інфармацыю, якая магла бы дапамагчы распрацоўшчыкам."

#: ../apport/ui.py:1494
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1494
msgid "This problem was already reported to developers. Thank you!"
msgstr "Аб гэтай праблеме распрацоўнікам ужо вядома. Дзякуй!"

#: ../debian/tmp/usr/share/apport/apport-kde.py:469
#: ../debian/tmp/usr/share/apport/apport-kde.py:504
#: ../debian/tmp/usr/share/apport/apport-kde.py:524 ../kde/apport-kde.py:469
#: ../kde/apport-kde.py:504 ../kde/apport-kde.py:524 ../gtk/apport-gtk.ui.h:1
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:1
msgid "Apport"
msgstr "Apport"

#: ../gtk/apport-gtk.ui.h:2 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:2
msgid "Cancel"
msgstr "Скасаваць"

#: ../gtk/apport-gtk.ui.h:3 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:3
msgid "OK"
msgstr "Добра"

#: ../gtk/apport-gtk.ui.h:4 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:4
msgid "Crash report"
msgstr "Справаздача аб непаладцы"

#: ../gtk/apport-gtk.ui.h:5 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:5
msgid "<big><b>Sorry, an internal error happened.</b></big>"
msgstr "<big><b>Выбачайце, паўстала ўнутраная памылка.</b></big>"

#: ../gtk/apport-gtk.ui.h:8 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:8
msgid "Remember this in future"
msgstr ""

#: ../gtk/apport-gtk.ui.h:9 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:9
msgid "Ignore future problems of this program version"
msgstr "Ігнараваць далейшыя збоі ў гэтай версіі праграмы"

#: ../gtk/apport-gtk.ui.h:10 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:10
msgid "Relaunch this application"
msgstr ""

#: ../gtk/apport-gtk.ui.h:12 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:12
msgid "_Examine locally"
msgstr "_Лакальная праверка"

#: ../gtk/apport-gtk.ui.h:13 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:13
msgid "Don't send"
msgstr ""

#: ../gtk/apport-gtk.ui.h:15 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:15
msgid "<big><b>Collecting problem information</b></big>"
msgstr "<big><b>Збор інфармацыі аб няспраўнасці</b></big>"

#: ../gtk/apport-gtk.ui.h:16 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:16
msgid ""
"Information is being collected that may help the developers fix the problem "
"you report."
msgstr ""
"Адбываецца збор інфармацыі, якая можа дапамагчы распрацоўшчыкам выправіць "
"гэтую памылку."

#: ../bin/apport-cli.py:267 ../debian/tmp/usr/share/apport/apport-kde.py:435
#: ../kde/apport-kde.py:435 ../debian/tmp/usr/bin/apport-cli.py:267
#: ../gtk/apport-gtk.ui.h:17 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:17
msgid "Uploading problem information"
msgstr "Перадача інфармацыі аб непаладцы"

#: ../gtk/apport-gtk.ui.h:18 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:18
msgid "<big><b>Uploading problem information</b></big>"
msgstr "<big><b>Перадача звестак аб няспраўнасці</b></big>"

#: ../debian/tmp/usr/share/apport/apport-kde.py:436 ../kde/apport-kde.py:436
#: ../gtk/apport-gtk.ui.h:19 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:19
msgid ""
"The collected information is being sent to the bug tracking system. This "
"might take a few minutes."
msgstr ""
"Сабраныя дадзеныя перасылаюцца ў сістэму ўліку памылак. Гэта можа заняць "
"некалькі хвілін."

#: ../bin/apport-valgrind.py:37 ../debian/tmp/usr/bin/apport-valgrind.py:37
msgid "See man page for details."
msgstr "Глядзіце падрабязнасці ў старонках man"

#: ../bin/apport-valgrind.py:43 ../debian/tmp/usr/bin/apport-valgrind.py:43
msgid "specify the log file name produced by valgrind"
msgstr "вызначце імя log файлу valgrind"

#: ../bin/apport-valgrind.py:46 ../debian/tmp/usr/bin/apport-valgrind.py:46
msgid ""
"reuse a previously created sandbox dir (SDIR) or, if it does not exist, "
"create it"
msgstr ""
"выкарыстоўваць раней створаны каталог пясочніцы (SDIR) або стварыць яго калі "
"яго не існуе"

#: ../bin/apport-valgrind.py:50 ../debian/tmp/usr/bin/apport-valgrind.py:50
msgid ""
"do  not  create  or reuse a sandbox directory for additional debug symbols "
"but rely only on installed debug symbols."
msgstr ""
"не ствараць і не выкарыстоўваць каталог пясочніцы для дадатковых сімвалаў "
"адладкі, а спадзявацца толькі на устаноўленыя сімвалы адладкі."

#: ../bin/apport-valgrind.py:54 ../debian/tmp/usr/bin/apport-valgrind.py:54
msgid ""
"reuse a previously created cache dir (CDIR) or, if it does not exist, create "
"it"
msgstr ""
"выкарыстоўваць раней створаны каталог кэша (CDIR) або стварыць яго калі яго "
"не існуе"

#: ../bin/apport-valgrind.py:58 ../debian/tmp/usr/bin/apport-valgrind.py:58
msgid ""
"report download/install progress when installing packages into sandbox"
msgstr ""
"паказваць прагрэс загрузкі/ўстаноўкі пры ўсталёўцы пакетаў у пясочніцу"

#: ../bin/apport-valgrind.py:62 ../debian/tmp/usr/bin/apport-valgrind.py:62
msgid ""
"the executable that is run under valgrind's memcheck tool  for memory leak "
"detection"
msgstr ""
"выкананы файл, які запускаецца пад кантролем valgrind memcheck для "
"вызначэння уцечак памяці"

#: ../bin/apport-valgrind.py:66 ../bin/apport-retrace.py:65
#: ../debian/tmp/usr/bin/apport-retrace.py:65
#: ../debian/tmp/usr/bin/apport-valgrind.py:66
msgid ""
"Install an extra package into the sandbox (can be specified multiple times)"
msgstr ""
"Усталяваць у часовае асяроддзе дадатковы пакет (можа задавацца некалькі "
"разоў)"

#: ../bin/apport-valgrind.py:97 ../debian/tmp/usr/bin/apport-valgrind.py:97
#, python-format
msgid "Error: %s is not an executable. Stopping."
msgstr "Памылка: %s - не выканальны файл. Прыпынак."

#: ../apport/com.ubuntu.apport.policy.in.h:1
msgid "Collect system information"
msgstr "Сабраць сістэмную інфармацыю"

#: ../apport/com.ubuntu.apport.policy.in.h:2
msgid ""
"Authentication is required to collect system information for this problem "
"report"
msgstr ""
"Трэба даць права, каб сабраць патрэбныя дадзеныя для справаздачнасці гэтай "
"праблемы"

#: ../apport/com.ubuntu.apport.policy.in.h:3
msgid "System problem reports"
msgstr "Справаздачы аб сістэмных памылках"

#: ../apport/com.ubuntu.apport.policy.in.h:4
msgid ""
"Please enter your password to access problem reports of system programs"
msgstr ""
"Калі ласка, увядзіце пароль для доступу да справаздач пра памылкі ў "
"сістэмных праграмах"

#: ../bin/apport-unpack.py:22 ../debian/tmp/usr/bin/apport-unpack.py:22
#, python-format
msgid "Usage: %s <report> <target directory>"
msgstr "Выкарыстанне: %s <справаздача> <тэчка прызначэння>"

#: ../bin/apport-unpack.py:42 ../debian/tmp/usr/bin/apport-unpack.py:42
msgid "Destination directory exists and is not empty."
msgstr "Тэчка прызначэння існуе і яна не пустая."

#: ../data/general-hooks/ubuntu.py:195
#: ../debian/tmp/usr/share/apport/general-hooks/ubuntu.py:195
msgid ""
"An Ubuntu package has a file conflict with a package that is not a genuine "
"Ubuntu package."
msgstr ""
"Пакет Ubuntu канфліктуе з пакетам, які не з'яўляецца сапраўдным пакетам "
"Ubuntu."

#: ../data/general-hooks/ubuntu.py:203
#: ../debian/tmp/usr/share/apport/general-hooks/ubuntu.py:203
msgid "You have already encountered this package installation failure."
msgstr "Памылка з усталёўкай гэтага пакета ўжо адбывалася."

#: ../data/general-hooks/ubuntu.py:219
#: ../debian/tmp/usr/share/apport/general-hooks/ubuntu.py:219
msgid ""
"Your system was initially configured with grub version 2, but you have "
"removed it from your system in favor of grub 1 without configuring it.  To "
"ensure your bootloader configuration is updated whenever a new kernel is "
"available, open a terminal and run:\n"
"\n"
"      sudo apt-get install grub-pc\n"
msgstr ""
"Першапачаткова сістэма была настроена на выкарыстанне загрузчыка GRUB версіі "
"2, але быў заменены на GRUB 1 і не настроена. Каб пераканацца ў "
"працаздольнасці загрузніка з новымі параметрамі, адкрыйце тэрмінал і "
"выканайце каманду:\n"
"\n"
"      sudo apt-get install grub-pc\n"

#: ../gtk/apport-gtk.desktop.in.h:1 ../kde/apport-kde.desktop.in.h:1
#: ../kde/apport-kde-mime.desktop.in.h:1
msgid "Report a problem..."
msgstr "Паведаміць аб праблеме..."

#: ../gtk/apport-gtk.desktop.in.h:2 ../kde/apport-kde.desktop.in.h:2
#: ../kde/apport-kde-mime.desktop.in.h:2
msgid "Report a malfunction to the developers"
msgstr "Паведаміць аб недапрацоўцы распрацоўшчыкам"

#: ../debian/tmp/usr/share/apport/apport-kde.py:234 ../kde/apport-kde.py:234
msgid "Leave Closed"
msgstr "Пакінуць зачыненым"

#: ../debian/tmp/usr/share/apport/apport-kde.py:235
#: ../debian/tmp/usr/share/apport/apport-kde.py:381 ../kde/apport-kde.py:235
#: ../kde/apport-kde.py:381
msgid "Relaunch"
msgstr "Перазапусціць"

#: ../debian/tmp/usr/share/apport/apport-kde.py:315 ../kde/apport-kde.py:315
msgid "Username:"
msgstr "Імя карыстальніка:"

#: ../debian/tmp/usr/share/apport/apport-kde.py:316 ../kde/apport-kde.py:316
msgid "Password:"
msgstr "Пароль:"

#: ../debian/tmp/usr/share/apport/apport-kde.py:406 ../kde/apport-kde.py:406
msgid "Collecting Problem Information"
msgstr "Збор інфармацыі аб праблеме"

#: ../bin/apport-cli.py:254 ../debian/tmp/usr/share/apport/apport-kde.py:407
#: ../kde/apport-kde.py:407 ../debian/tmp/usr/bin/apport-cli.py:254
msgid "Collecting problem information"
msgstr "Збор інфармацыі аб праблеме"

#: ../debian/tmp/usr/share/apport/apport-kde.py:408 ../kde/apport-kde.py:408
msgid ""
"The collected information can be sent to the developers to improve the "
"application. This might take a few minutes."
msgstr ""
"Сабраную інфармацыю можна даслаць распрацоўшчыкам, каб палепшыць "
"прыкладанне. Гэта можа заняць некалькі хвілін."

#: ../debian/tmp/usr/share/apport/apport-kde.py:434 ../kde/apport-kde.py:434
msgid "Uploading Problem Information"
msgstr "Перадача інфармацыі аб непаладцы"

#: ../debian/tmp/usr/share/apport/apportcheckresume.py:67
#: ../data/apportcheckresume.py:67
msgid ""
"This occurred during a previous suspend, and prevented the system from "
"resuming properly."
msgstr ""
"Гэта адбылося падчас папярэдняга сеансу прыпынення працы і прывяло да "
"немагчымасці належнага аднаўлення працы сістэмы."

#: ../debian/tmp/usr/share/apport/apportcheckresume.py:69
#: ../data/apportcheckresume.py:69
msgid ""
"This occurred during a previous hibernation, and prevented the system from "
"resuming properly."
msgstr ""
"Гэта адбылося падчас папярэдняга сеансу ўсыплення і прывяло да немагчымасці "
"належнага аднаўлення працы сістэмы."

#: ../debian/tmp/usr/share/apport/apportcheckresume.py:74
#: ../data/apportcheckresume.py:74
msgid ""
"The resume processing hung very near the end and will have appeared to have "
"completed normally."
msgstr ""
"Адбылася памылка ў працэсе стварэння справаздачы, бо сам працэс завіс перад "
"сваім завяршэннем; для нармальнага завяршэння ён павінен быў з'явіцца."

#: ../bin/apport-cli.py:80 ../debian/tmp/usr/bin/apport-cli.py:80
msgid "Press any key to continue..."
msgstr "Каб працягнуць, націсніце любую клавішу ..."

#: ../bin/apport-cli.py:87 ../debian/tmp/usr/bin/apport-cli.py:87
msgid "What would you like to do? Your options are:"
msgstr "Што вы жадаеце зрабіць? Магчымыя варыянты:"

#: ../bin/apport-cli.py:100 ../debian/tmp/usr/bin/apport-cli.py:100
#, python-format
msgid "Please choose (%s):"
msgstr "Калі ласка выберыце (%s):"

#: ../bin/apport-cli.py:164 ../debian/tmp/usr/bin/apport-cli.py:164
#, python-format
msgid "(%i bytes)"
msgstr "(%i байт)"

#: ../bin/apport-cli.py:195 ../debian/tmp/usr/bin/apport-cli.py:195
msgid ""
"After the problem report has been sent, please fill out the form in the\n"
"automatically opened web browser."
msgstr ""
"Пасля таго, як справаздача будзе дасланая, запоўніце\n"
"форму ў акне браўзэра , што адчынілася аўтаматычна."

#: ../bin/apport-cli.py:198 ../debian/tmp/usr/bin/apport-cli.py:198
#, python-format
msgid "&Send report (%s)"
msgstr "&Даслаць паведамленне (%s)"

#: ../bin/apport-cli.py:202 ../debian/tmp/usr/bin/apport-cli.py:202
msgid "&Examine locally"
msgstr "&Локальна перевірка"

#: ../bin/apport-cli.py:206 ../debian/tmp/usr/bin/apport-cli.py:206
msgid "&View report"
msgstr "&Паказаць справаздачу"

#: ../bin/apport-cli.py:207 ../debian/tmp/usr/bin/apport-cli.py:207
msgid "&Keep report file for sending later or copying to somewhere else"
msgstr ""
"&Захаваць файл справаздачы для наступнай адпраўкі альбо капіявання куды-"
"небудзь"

#: ../bin/apport-cli.py:208 ../debian/tmp/usr/bin/apport-cli.py:208
msgid "Cancel and &ignore future crashes of this program version"
msgstr "Адмяніць і &ігнараваць будучыя збоі ў гэтай версіі праграмы"

#: ../bin/apport-cli.py:210 ../bin/apport-cli.py:287 ../bin/apport-cli.py:319
#: ../bin/apport-cli.py:340 ../debian/tmp/usr/bin/apport-cli.py:210
#: ../debian/tmp/usr/bin/apport-cli.py:287
#: ../debian/tmp/usr/bin/apport-cli.py:319
#: ../debian/tmp/usr/bin/apport-cli.py:340
msgid "&Cancel"
msgstr "&Скасаваць"

#: ../bin/apport-cli.py:238 ../debian/tmp/usr/bin/apport-cli.py:238
msgid "Problem report file:"
msgstr "Файл справаздачы аб праблеме:"

#: ../bin/apport-cli.py:244 ../bin/apport-cli.py:249
#: ../debian/tmp/usr/bin/apport-cli.py:244
#: ../debian/tmp/usr/bin/apport-cli.py:249
msgid "&Confirm"
msgstr "&Пацвердзіць"

#: ../bin/apport-cli.py:248 ../debian/tmp/usr/bin/apport-cli.py:248
#, python-format
msgid "Error: %s"
msgstr "Памылка: %s"

#: ../bin/apport-cli.py:255 ../debian/tmp/usr/bin/apport-cli.py:255
msgid ""
"The collected information can be sent to the developers to improve the\n"
"application. This might take a few minutes."
msgstr ""
"Сабраная інфармацыя можа быць накіравана распрацоўшчыкам для\n"
"паляпшэння дастасавання. Гэта можа заняць некалькі хвілін."

#: ../bin/apport-cli.py:268 ../debian/tmp/usr/bin/apport-cli.py:268
msgid ""
"The collected information is being sent to the bug tracking system.\n"
"This might take a few minutes."
msgstr ""
"Сабраная інфармацыя накіроўваецца да сістэмы адсочвання памылак.\n"
"Гэта можа заняць некалькі хвілін."

#: ../bin/apport-cli.py:318 ../debian/tmp/usr/bin/apport-cli.py:318
msgid "&Done"
msgstr "&Зроблена"

#: ../bin/apport-cli.py:324 ../debian/tmp/usr/bin/apport-cli.py:324
msgid "none"
msgstr "нічога"

#: ../bin/apport-cli.py:325 ../debian/tmp/usr/bin/apport-cli.py:325
#, python-format
msgid "Selected: %s. Multiple choices:"
msgstr "Абрана: %s. Некалькі варыянтаў:"

#: ../bin/apport-cli.py:341 ../debian/tmp/usr/bin/apport-cli.py:341
msgid "Choices:"
msgstr "Выбар:"

#: ../bin/apport-cli.py:355 ../debian/tmp/usr/bin/apport-cli.py:355
msgid "Path to file (Enter to cancel):"
msgstr "Шлях да файла (Enter — адмена):"

#: ../bin/apport-cli.py:361 ../debian/tmp/usr/bin/apport-cli.py:361
msgid "File does not exist."
msgstr "Файл не існуе."

#: ../bin/apport-cli.py:363 ../debian/tmp/usr/bin/apport-cli.py:363
msgid "This is a directory."
msgstr "Гэта - дырэкторыя."

#: ../bin/apport-cli.py:369 ../debian/tmp/usr/bin/apport-cli.py:369
msgid "To continue, you must visit the following URL:"
msgstr "Каб працягнуць, Вы павінны наведаць наступны адрас:"

#: ../bin/apport-cli.py:371 ../debian/tmp/usr/bin/apport-cli.py:371
msgid ""
"You can launch a browser now, or copy this URL into a browser on another "
"computer."
msgstr ""
"Зараз Вы можаце адкрыць браўзар ці скапіяваць URL у браўзар на іншы кампутар."

#: ../bin/apport-cli.py:373 ../debian/tmp/usr/bin/apport-cli.py:373
msgid "Launch a browser now"
msgstr "Запусціць браўзар"

#: ../bin/apport-cli.py:388 ../debian/tmp/usr/bin/apport-cli.py:388
msgid "No pending crash reports. Try --help for more information."
msgstr "Няма чакаючых паведамленьняў аб збоях. Паспрабуйце ключ --help."

#: ../bin/apport-retrace.py:34 ../debian/tmp/usr/bin/apport-retrace.py:34
msgid "Do not put the new traces into the report, but write them to stdout."
msgstr ""
"Не дадаваць новыя трасіроўкі ў справаздачу, а адсылаць на стандартны вывад."

#: ../bin/apport-retrace.py:36 ../debian/tmp/usr/bin/apport-retrace.py:36
msgid ""
"Start an interactive gdb session with the report's core dump (-o ignored; "
"does not rewrite report)"
msgstr ""
"Запусціць інтэрактыўны сеанс gdb з дампам ядра са справаздачы (-o "
"ігнаруецца; справаздача не перазапісваецца)"

#: ../bin/apport-retrace.py:38 ../debian/tmp/usr/bin/apport-retrace.py:38
msgid ""
"Write modified report to given file instead of changing the original report"
msgstr ""
"Захаваць змененую справаздачу ў файл замест змены арыгінальнай справаздачы"

#: ../bin/apport-retrace.py:41 ../debian/tmp/usr/bin/apport-retrace.py:41
msgid "Remove the core dump from the report after stack trace regeneration"
msgstr "Выдаліць дамп ядра са справаздачы пасля ўзнаўлення трасіроўкі стэка"

#: ../bin/apport-retrace.py:43 ../debian/tmp/usr/bin/apport-retrace.py:43
msgid "Override report's CoreFile"
msgstr "Замяніць CoreFile у справаздачы"

#: ../bin/apport-retrace.py:45 ../debian/tmp/usr/bin/apport-retrace.py:45
msgid "Override report's ExecutablePath"
msgstr "Замяніць ExecutablePath у справаздачы"

#: ../bin/apport-retrace.py:47 ../debian/tmp/usr/bin/apport-retrace.py:47
msgid "Override report's ProcMaps"
msgstr "Замяніць ProcMaps у справаздачы"

#: ../bin/apport-retrace.py:49 ../debian/tmp/usr/bin/apport-retrace.py:49
msgid "Rebuild report's Package information"
msgstr "Нанава пабудаваць інфармацыю аб пакетах у справаздачы"

#: ../bin/apport-retrace.py:51 ../debian/tmp/usr/bin/apport-retrace.py:51
msgid ""
"Build a temporary sandbox and download/install the necessary packages and "
"debug symbols in there; without this option it assumes that the necessary "
"packages and debug symbols are already installed in the system. The argument "
"points to the packaging system configuration base directory; if you specify "
"\"system\", it will use the system configuration files, but will then only "
"be able to retrace crashes that happened on the currently running release."
msgstr ""
"Стварыць часавае асяроддзе, затым загрузіць / ўсталяваць у яе неабходныя "
"пакеты і адладкавыя сімвалы; без гэтага параметра прадугледжваецца, што "
"неабходныя пакеты і адладкавыя сімвалы ў сістэме ўжо ўсталяваныя. Аргумент "
"паказвае на базавую тэчку канфігурацыі сістэмы пакетаў; калі Вы паказалі "
"\"system\", будуць выкарыстоўвацца сістэмныя файлы канфігурацыі, але толькі "
"ў выпадку выяўлення аварыйных сітуацый, якія адбыліся ў выпуску сістэмы, які "
"працуе ў дадзены момант."

#: ../bin/apport-retrace.py:53 ../debian/tmp/usr/bin/apport-retrace.py:53
msgid ""
"Build another temporary sandbox for installing gdb and its dependencies "
"using the same release as the report rather than whatever version of gdb you "
"have installed."
msgstr ""

#: ../bin/apport-retrace.py:55 ../debian/tmp/usr/bin/apport-retrace.py:55
msgid ""
"Report download/install progress when installing packages into sandbox"
msgstr ""
"Паведамляць аб ходзе выканання загрузкі / ўсталёўкі пакетаў у часовае "
"асяроддзе"

#: ../bin/apport-retrace.py:57 ../debian/tmp/usr/bin/apport-retrace.py:57
msgid "Prepend timestamps to log messages, for batch operation"
msgstr ""
"Дадаваць часовыя пазнакі да паведамленняў у часопісе, для групавых аперацый"

#: ../bin/apport-retrace.py:59 ../debian/tmp/usr/bin/apport-retrace.py:59
msgid ""
"Create and use third-party repositories from origins specified in reports"
msgstr ""
"Стварэнне і выкарыстанне іншых сховішчаў на аснове зыходных, указаных у "
"справаздачах"

#: ../bin/apport-retrace.py:61 ../debian/tmp/usr/bin/apport-retrace.py:61
msgid "Cache directory for packages downloaded in the sandbox"
msgstr "Тэчка для захавання пакетаў, загружаных у часовае асяроддзе"

#: ../bin/apport-retrace.py:63 ../debian/tmp/usr/bin/apport-retrace.py:63
msgid ""
"Directory for unpacked packages. Future runs will assume that any already "
"downloaded package is also extracted to this sandbox."
msgstr ""
"Дырэкторыя для распакавання пакетаў. Пры наступных запусках ўсё ўжо "
"загружаны пакеты будуць распакоўваць ў гэта ізаляванае асяроддзе."

#: ../bin/apport-retrace.py:67 ../debian/tmp/usr/bin/apport-retrace.py:67
msgid ""
"Path to a file with the crash database authentication information. This is "
"used when specifying a crash ID to upload the retraced stack traces (only if "
"neither -g, -o, nor -s are specified)"
msgstr ""
"Шлях да файла з інфармацыяй аб праверцы сапраўднасці базы збояў. "
"Выкарыстоўваецца пры ўказанні ID збою для адпраўкі трасіровак стэка (толькі "
"калі -g, -o ці -s не пазначаныя)"

#: ../bin/apport-retrace.py:69 ../debian/tmp/usr/bin/apport-retrace.py:69
msgid ""
"Display retraced stack traces and ask for confirmation before sending them "
"to the crash database."
msgstr ""
"Адлюстраваць трасіроўкі і запытаць пацверджанне перад іх адпраўкай у базу "
"дадзеных збояў."

#: ../bin/apport-retrace.py:71 ../debian/tmp/usr/bin/apport-retrace.py:71
msgid ""
"Path to the duplicate sqlite database (default: no duplicate checking)"
msgstr ""
"Шлях да дублюючай базы дадзеных sqlite (па змаўчанні: без праверкі "
"дублікатаў)"

#: ../bin/apport-retrace.py:73 ../debian/tmp/usr/bin/apport-retrace.py:73
msgid "Do not add StacktraceSource to the report."
msgstr ""

#: ../bin/apport-retrace.py:82 ../debian/tmp/usr/bin/apport-retrace.py:82
msgid "You cannot use -C without -S. Stopping."
msgstr "Нельга выкарыстоўваць -C без -S. Прыпынак."

#. translators: don't translate y/n, apport currently only checks for "y"
#: ../bin/apport-retrace.py:115 ../debian/tmp/usr/bin/apport-retrace.py:115
msgid "OK to send these as attachments? [y/n]"
msgstr "Адправіць гэтыя дастасаванні? [y/n]"

#: ../data/kernel_oops.py:29 ../debian/tmp/usr/share/apport/kernel_oops.py:29
msgid "Your system might become unstable now and might need to be restarted."
msgstr "Сістэма можа стаць нестабільнай, магчыма спатрэбіцца перазагрузка."

#: ../kde/apport-kde-mimelnk.desktop.in.h:1
msgid "Apport crash file"
msgstr "Файл справаздачы Apport"
